export const DESTINATIONS = [
  {
    name: "Boracay", slug: "boracay", tagline: "World-famous white beach paradise",
    image: "https://images.unsplash.com/photo-1519046904884-53103b34b206?w=1200&q=90&fit=crop",
    hero: "https://images.unsplash.com/photo-1519046904884-53103b34b206?w=1200&q=90&fit=crop",
    itinerary: ["White Beach sunrise walk", "Island hopping tour", "Snorkeling at Crystal Cove", "Sunset at Willy's Rock", "Night market at D'Mall", "Paraw sailing experience", "Puka Shell Beach visit"],
  },
  {
    name: "Bantayan", slug: "bantayan", tagline: "Pristine island escape in Cebu",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&q=80&fit=crop",
    hero: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1400&q=90&fit=crop",
    itinerary: ["Santa Fe Beach exploration", "Virgin Island sandbar tour", "Ogtong Cave swimming", "Bantayan Church visit", "Kota Beach sunset", "Fresh seafood dinner", "Island bike tour"],
  },
  {
    name: "Batanes", slug: "batanes", tagline: "The rugged beauty of the northernmost isles",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80&fit=crop",
    hero: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1400&q=90&fit=crop",
    itinerary: ["Basco Lighthouse sunrise", "Vayang Rolling Hills", "Nakabuang Arch & Sabtang Island", "Chavayan Village walk", "Honesty Coffee Shop", "Marlboro Hills panorama", "Valugan Boulder Beach"],
  },
  {
    name: "Bacolod", slug: "bacolod", tagline: "The City of Smiles awaits you",
    image: "https://images.unsplash.com/photo-1483683804023-6ccdb62f86ef?w=1200&q=90&fit=crop",
    hero: "https://images.unsplash.com/photo-1483683804023-6ccdb62f86ef?w=1200&q=90&fit=cropp",
    itinerary: ["Ruins of Talisay (The Taj Mahal of Negros)", "Masskara Festival Museum", "Mambukal Resort hot springs", "Silay Heritage Houses tour", "Bacolod Public Plaza", "Chicken Inasal food tour", "San Sebastian Cathedral"],
  },
  {
    name: "Bohol", slug: "bohol", tagline: "Chocolate Hills and tarsier wonders",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=1200&q=90&fit=crop",
    hero: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=1200&q=90&fit=crop",
    itinerary: ["Chocolate Hills viewpoint at sunrise", "Philippine Tarsier Sanctuary", "Loboc River lunch cruise", "Baclayon Church", "Panglao Island beaches", "Hinagdanan Cave", "Blood Compact Shrine"],
  },
  {
    name: "Cebu", slug: "cebu", tagline: "Queen City of the South",
    image: "https://images.unsplash.com/photo-1555400038-63f5ba517a47?w=600&q=80&fit=crop",
    hero: "https://images.unsplash.com/photo-1555400038-63f5ba517a47?w=1400&q=90&fit=crop",
    itinerary: ["Magellan's Cross & Basilica del Santo Niño", "Whale shark watching in Oslob", "Kawasan Falls canyoneering", "Tops Lookout at night", "Carbon Market food tour", "Moalboal diving", "Fort San Pedro"],
  },
  {
    name: "Camiguin", slug: "camiguin", tagline: "Island born of fire, surrounded by sea",
    image: "https://images.unsplash.com/photo-1516690561799-46d8f74f9abf?w=600&q=80&fit=crop",
    hero: "https://images.unsplash.com/photo-1516690561799-46d8f74f9abf?w=1400&q=90&fit=crop",
    itinerary: ["White Island sandbar snorkeling", "Sunken Cemetery dive", "Ardent Hot Spring soak", "Katibawasan Falls hike", "Old Volcano trek", "Sto. Niño Cold Spring", "Mantigue Island day trip"],
  },
  {
    name: "Northern Mindanao", slug: "northern-mindanao", tagline: "Gateway to the heart of Mindanao",
    image: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?w=600&q=80&fit=crop",
    hero: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?w=1400&q=90&fit=crop",
    itinerary: ["Lake Lanao cruise", "Initao-Libertad Protected Landscape", "Macajalar Bay scenic drive", "Xavier University Cultural Tour", "Opol Beach sunset", "Gaston Park heritage walk", "Del Monte Pineapple Plantation"],
  },
  {
    name: "Coron", slug: "coron", tagline: "Crystal lagoons and legendary shipwrecks",
    image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=600&q=80&fit=crop",
    hero: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=1400&q=90&fit=crop",
    itinerary: ["Twin Lagoon kayaking", "Kayangan Lake snorkeling (clearest in Asia)", "WWII Japanese shipwreck diving", "Barracuda Lake thermocline dive", "Coron Town snorkeling tour", "Siete Pecados Marine Park", "Mount Tapyas sunset trek"],
  },
  {
    name: "Cagayan de Oro", slug: "cagayan-de-oro", tagline: "The City of Golden Friendship",
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&q=80&fit=crop",
    hero: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1400&q=90&fit=crop",
    itinerary: ["Cagayan de Oro River whitewater rafting", "Mapawa Nature Park canopy walk", "Dahilayan Adventure Park zipline", "Seven Falls Bukidnon day trip", "Night market food crawl", "Cugman Falls hike", "Macahambus Gorge & Cave"],
  },
  {
    name: "Davao", slug: "davao", tagline: "The King City of the South",
    image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=600&q=80&fit=crop",
    hero: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1400&q=90&fit=crop",
    itinerary: ["Philippine Eagle Center visit", "Mt. Apo sunrise trek (Day 1)", "Mt. Apo summit (Day 2)", "Eden Nature Park", "Samal Island resort day", "Davao durian food tour", "People's Park & Magsaysay Park"],
  },
  {
    name: "Dinagat", slug: "dinagat", tagline: "Untouched island beauty",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=90&fit=crop",
    hero: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=90&fit=crop",
    itinerary: ["Tinago Falls hike", "Basilisa coastline boat tour", "Cagdianao Heritage Trail", "Loreto limestone cave exploration", "San Jose Bay island hopping", "Balite Beach sunset", "Sohoton-style sea caves tour"],
  },
  {
    name: "Catanduanes", slug: "catanduanes", tagline: "The happy island of the Pacific",
    image: "https://images.unsplash.com/photo-1505118380757-91f5f5632de0?w=600&q=80&fit=crop",
    hero: "https://images.unsplash.com/photo-1505118380757-91f5f5632de0?w=1400&q=90&fit=crop",
    itinerary: ["Puraran Beach surfing (world-class barrels)", "Binurong Point cliffside views", "Bato Church & Heritage Trail", "Hicming Falls trek", "Luyang Bat Cave", "Balongbong Beach sunset", "Porog Falls adventure"],
  },
  {
    name: "Bukidnon", slug: "bukidnon", tagline: "The highland paradise of Mindanao",
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&q=80&fit=crop",
    hero: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1400&q=90&fit=crop",
    itinerary: ["Dahilayan Adventure Park zip (Asia's longest twin zip)", "Monastery of Transfiguration", "Del Monte Pineapple Plantation tour", "Seven Falls Sinabugan", "Kitanglad Range hike", "Talakag Horse Riding", "Kaamulan Cultural Festival experience"],
  },
  {
    name: "Leyte", slug: "leyte", tagline: "Historic shores and lush landscapes",
    image: "https://images.unsplash.com/photo-1519046904884-53103b34b206?w=600&q=80&fit=crop",
    hero: "https://images.unsplash.com/photo-1519046904884-53103b34b206?w=1400&q=90&fit=crop",
    itinerary: ["MacArthur Landing Memorial", "Sohoton Natural Bridge National Park", "Kalanggaman Island sandbar", "San Juanico Bridge scenic walk", "Basey Caves Samar day trip", "Tacloban Heritage Tour", "Lake Danao hike"],
  },
  {
    name: "Port Barton", slug: "port-barton", tagline: "Palawan's hidden cinematic gem",
    image: "https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?w=600&q=80&fit=crop",
    hero: "https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?w=1400&q=90&fit=crop",
    itinerary: ["Albaguen Island snorkeling", "German Island beach day", "Exotic Island bioluminescence night swim", "Hidden waterfalls jungle trek", "Long Beach sunset walk", "Open water reef dive", "Firefly watching kayak tour"],
  },
  {
    name: "Legazpi", slug: "legazpi", tagline: "In the shadow of Mayon Volcano",
    image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=600&q=80&fit=crop",
    hero: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1400&q=90&fit=crop",
    itinerary: ["Mayon Volcano panorama at dawn", "Lignon Hill Nature Park", "Cagsawa Ruins sunrise", "Sumlang Lake kayaking", "Misibis Bay resort afternoon", "Daraga Church heritage visit", "ATV Mayon Skyline adventure"],
  },
  {
    name: "Manila", slug: "manila", tagline: "The pearl of the Orient Seas",
    image: "https://images.unsplash.com/photo-1555400038-63f5ba517a47?w=600&q=80&fit=crop",
    hero: "https://images.unsplash.com/photo-1555400038-63f5ba517a47?w=1400&q=90&fit=crop",
    itinerary: ["Intramuros walking tour & Fort Santiago", "Rizal Park & National Museum", "BGC street art & galleries", "Manila Bay sunset walk", "Binondo Chinatown food tour", "San Agustin Church UNESCO visit", "Bonifacio Global City night life"],
  },
  {
    name: "Siargao", slug: "siargao", tagline: "The surfing capital of the Philippines",
    image: "https://images.unsplash.com/photo-1502680390469-be75c86b636f?w=600&q=80&fit=crop",
    hero: "https://images.unsplash.com/photo-1502680390469-be75c86b636f?w=1400&q=90&fit=crop",
    itinerary: ["Cloud 9 surfing & boardwalk", "Sohoton Cove bioluminescence", "Naked Island & Daku Island hopping", "Magpupungko Rock Pools", "Sugba Lagoon paddleboarding", "Pacifico Beach north surf", "Siargao town firefly tour"],
  },
  {
    name: "Samal", slug: "samal", tagline: "Island Garden City of Samal",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&q=80&fit=crop",
    hero: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1400&q=90&fit=crop",
    itinerary: ["Hagimit Falls jungle swim", "Pearl Farm Beach Resort day tour", "Monfort Bat Cave (world's largest colony)", "Vanishing Island sandbar", "Coral Garden snorkeling", "Maxima Aquafun water sports", "Sunset Beach bonfire evening"],
  },
  {
    name: "Ilo-Ilo", slug: "ilo-ilo", tagline: "Heritage, culture, and breathtaking coastlines",
    image: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=1200&q=90&fit=crop",
    hero: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=1200&q=90&fit=crop",
    itinerary: ["Molo Church & Mansion heritage walk", "Miag-ao Church UNESCO site", "Guimaras Island mango farm tour", "Dinagyang Festival cultural immersion", "Smallville nightlife district", "Iloilo River Esplanade sunset", "La Paz Batchoy food tour"],
  },
  {
    name: "Balabac", slug: "balabac", tagline: "Palawan's last frontier",
    image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=600&q=80&fit=crop",
    hero: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=1400&q=90&fit=crop",
    itinerary: ["Onuk Island pink sand beach", "Patanlungan Island snorkeling", "Candaraman Island overnight camp", "Melville Lighthouse hike", "Bugsuk Island wildlife watch", "Ramos Island turtles", "Pandanan Island beach day"],
  },
  {
    name: "Puerto Princesa", slug: "puerto-princesa", tagline: "Home of the Underground River",
    image: "https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?w=600&q=80&fit=crop",
    hero: "https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?w=1400&q=90&fit=crop",
    itinerary: ["Puerto Princesa Subterranean River (UNESCO)", "Honda Bay island hopping", "Firefly watching Iwahig River", "Crocodile Farm & Nature Park", "Ugong Rock climbing & zipline", "Baker's Hill panoramic gardens", "Mitra's Ranch sunset"],
  },
  {
    name: "El Nido", slug: "el-nido", tagline: "Limestone cliffs and emerald lagoons",
    image: "https://images.unsplash.com/photo-1559128010-7c1ad6e1b6a5?w=600&q=80&fit=crop",
    hero: "https://images.unsplash.com/photo-1559128010-7c1ad6e1b6a5?w=1400&q=90&fit=crop",
    itinerary: ["Big Lagoon kayaking Tour A", "Small Lagoon snorkeling", "Secret Lagoon swim", "Cadlao Lagoon cliff jump", "Shimizu Island coral reef", "Matinloc Shrine cliff views", "Las Cabañas Beach sunset"],
  },
  {
    name: "Biliran", slug: "biliran", tagline: "Waterfalls and volcanic hot springs",
    image: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?w=600&q=80&fit=crop",
    hero: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?w=1400&q=90&fit=crop",
    itinerary: ["Ulan-Ulan Falls trek", "Tomalistis Falls multi-tiered swim", "Libtong Hot Spring soak", "Higatangan Island sandbar", "Almeria Rice Terraces", "Biliran Volcano nature hike", "Naval town cultural walk"],
  },
  {
    name: "Mt. Apo", slug: "mt-apo", tagline: "The roof of the Philippines",
    image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=600&q=80&fit=crop",
    hero: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1400&q=90&fit=crop",
    itinerary: ["Kidapawan jumpoff registration & camp setup", "Mainit Hot Spring soak (Day 1)", "Lake Venado crater camp (Day 2)", "Summit push at 2,954m (Day 3)", "Summit sunrise panorama", "Bouldering zone & sulphuric springs", "Descent & celebration dinner"],
  },
  {
    name: "Dumaguete", slug: "dumaguete", tagline: "The city of gentle people",
    image: "https://images.unsplash.com/photo-1516690561799-46d8f74f9abf?w=600&q=80&fit=crop",
    hero: "https://images.unsplash.com/photo-1516690561799-46d8f74f9abf?w=1400&q=90&fit=crop",
    itinerary: ["Apo Island marine sanctuary diving", "Twin Lakes Balinsasayaw & Danao", "Liberty Bell Park boulevard stroll", "Casaroro Falls jungle hike", "Manjuyod White Sandbar island", "Silliman University campus tour", "Sans Rival Cakes & Pastries food stop"],
  },
  {
    name: "Siquijor", slug: "siquijor", tagline: "The mystical island of fire",
    image: "https://images.unsplash.com/photo-1519046904884-53103b34b206?w=600&q=80&fit=crop",
    hero: "https://images.unsplash.com/photo-1519046904884-53103b34b206?w=1400&q=90&fit=crop",
    itinerary: ["Cambugahay Falls natural slide", "Paliton Beach sunset (PH's finest)", "Salagdoong Beach cliff jumping", "Century-old Balete tree swim", "Lazi Convent & Church UNESCO", "Lugnason Falls bamboo forest", "Healing potion ritual with local shaman"],
  },
  {
    name: "General Santos", slug: "general-santos", tagline: "The tuna capital of the Philippines",
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&q=80&fit=crop",
    hero: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1400&q=90&fit=crop",
    itinerary: ["General Santos Fish Port tuna auction", "Sarangani Bay scenic walk", "Lake Sebu Seven Falls", "T'boli weaving village cultural tour", "Gumasa Beach Glan resort day", "Mt. Matutum base camp hike", "Socsksargen Heritage Trail"],
  },
  {
    name: "Malapascua", slug: "malapascua", tagline: "Where thresher sharks meet paradise",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&q=80&fit=crop",
    hero: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1400&q=90&fit=crop",
    itinerary: ["Monad Shoal thresher shark dive at dawn", "Dakit-Dakit Island snorkeling", "Calanggaman Island day trip", "Bounty Beach sunset swim", "Lighthouse Beach picnic", "Night dive manta rays", "Local fishing village walk"],
  },
  {
    name: "Zamboanga", slug: "zamboanga", tagline: "Asia's Latin city by the sea",
    image: "https://images.unsplash.com/photo-1521295121783-8a321d551ad2?w=1200&q=90&fit=crop",
    hero: "https://images.unsplash.com/photo-1521295121783-8a321d551ad2?w=1200&q=90&fit=crop",
    itinerary: ["Great Santa Cruz Island pink sand beach", "Little Santa Cruz Island birdwatching", "Fort Pilar Shrine heritage tour", "Rio Hondo Water Village cultural walk", "Paseo del Mar boardwalk sunset", "Vinta boat race festival", "Yakan weaving handicraft village"],
  },
  {
    name: "Basilan", slug: "basilan", tagline: "A hidden gem of the Sulu Archipelago",
    image: "https://images.unsplash.com/photo-1505118380757-91f5f5632de0?w=600&q=80&fit=crop",
    hero: "https://images.unsplash.com/photo-1505118380757-91f5f5632de0?w=1400&q=90&fit=crop",
    itinerary: ["Isabela City heritage trail", "Malamawi Island beach day", "Yakan cultural village visit", "Basilan Rubber Plantation", "Kumalarang Falls hike", "Tipo-Tipo mangrove kayak", "Local Yakan delicacy food tour"],
  },
];