export const DESTINATIONS = [
  {
    name: "Boracay", slug: "boracay", tagline: "World-famous white beach paradise",
    image: "https://images.unsplash.com/photo-1519046904884-53103b34b206?w=1200&q=90&fit=crop",
    hero: "https://images.unsplash.com/photo-1519046904884-53103b34b206?w=1200&q=90&fit=crop",
    videoUrl: "https://bit.ly/GDX-BORACAY-VID",
    package: "3D2N Boracay Land Arrangement",
    hotelCategories: [
      { label: "Budget", note: "Budget Inn / Transient – No Breakfast", hotels: "Villa Simprosa, Jerome's Bungalow, Island Inn (Stn 2), Wendy's Apartelle (Stn 3)", rates: [{ label: "Buy 2 Take 2", price: "₱5,699/person" }, { label: "Buy 2 Take 1", price: "₱4,724/person" }] },
      { label: "Standard & Midrange", hotels: "Diamond Water Edge Resort, The Orient Beach Boracay, Canyon Hotel (Stn 1), La Carmela, Grand Boracay Resort, Abozza Resort (Stn 2), Golden Phoenix, Bamboo Beach, 357 Boracay, Erus Suites, Divegurus (Stn 3)", rates: [{ label: "Buy 2 Take 2", price: "₱9,099/person" }, { label: "Buy 2 Take 1", price: "₱6,974/person" }, { label: "Sneak-in Child (2–6 yrs)", price: "₱1,829" }] },
      { label: "Four Star A", hotels: "Patio Pacific (Stn 1), Boracay Tropics, Azalea Hotel, Lime Hotel (Stn 2), Paradise Garden Resort (Stn 3)", rates: [{ label: "Buy 2 Take 2", price: "₱11,099/person" }, { label: "Buy 2 Take 1", price: "₱7,949/person" }, { label: "Sneak-in Child (2–6 yrs)", price: "₱1,829" }] },
      { label: "Four Star B", hotels: "Microtel by Wyndham (Stn 0), Estacio Uno, Boracay Haven Suites, The Muse Hotel, Pinnacle Boracay, Four Points by Sheraton (Stn 1), Boracay Uptown, Le Soleil, Mandarin Nest, HUE Hotel (Stn 2), Boracay Ocean Club, Astoria Current, Boracay Sands (Stn 3)", rates: [{ label: "Buy 2 Take 2", price: "₱13,799/person" }, { label: "Buy 2 Take 1", price: "₱12,149/person" }, { label: "Sneak-in Child (2–6 yrs)", price: "₱1,829" }] },
      { label: "Five Star A", hotels: "Two Seasons Boracay Resort (Stn 1), Mandarin Bay Resort & Spa (Stn 2)", rates: [{ label: "Buy 2 Take 2", price: "₱19,499/person" }, { label: "Buy 2 Take 1", price: "₱15,149/person" }, { label: "Sneak-in Child (2–6 yrs)", price: "₱1,829" }] },
      { label: "Five Star B", hotels: "Movenpick Resort & Spa, Crimson Hotel (Stn 0)", rates: [{ label: "Buy 2 Take 1", price: "₱16,349/person" }, { label: "Sneak-in Child (2–6 yrs)", price: "₱1,829" }] },
    ],
    inclusions: ["3D2N Hotel Accommodation", "Daily Breakfast (except Budget & Abozza)", "Round Trip Land and Sea Transfers", "Hotel Taxes and Surcharges", "Complimentary Island Hopping (no lunch)", "Use of Kawa Hot Bath", "FREE Mermaid Photoshoot (subject to availability)"],
    exclusions: ["Hotel Security Deposit", "Snorkeling Gear", "Caticlan Terminal Fee (₱150/way)", "Environmental Fee (₱150)", "Buffet Lunch at Island Hopping (₱350)"],
    itinerary: [
      { day: "Day 1", title: "Arrival", details: "Arrival at Caticlan Airport, van transfer (15 mins) to Caticlan Jetty Port, boat transfer (15 mins) to Boracay Island, hotel check-in. Free time. Overnight." },
      { day: "Day 2", title: "Island Hopping", details: "Breakfast. Complimentary Island Hopping with Kawa Hot Bath. Pick up: 8:00–9:00 AM | Duration: 4–5 hrs.\n\nHABAGAT ROUTE: Ilig-Iligan / Puka Beach, Crocodile Island, Tabon Beach Lunch, Crystal Cove Island.\n\nAMIHAN ROUTE: Coral Garden, Balinghai Beach, Puka Beach, Tabon Beach Lunch, Crystal Cove Island." },
      { day: "Day 3", title: "Departure", details: "Breakfast. Free time or optional tours. Check-out, transfer to Caticlan Airport." },
    ],
    optionalTours: [{ name: "Aron's Magic Island", price: "₱250/person (on-site)" }, { name: "Crystal Cove Island Entrance", price: "₱300/person" }],
    notes: ["Snorkeling Fee: ₱100/person (collected at snorkeling site, one-time payment)", "Hotel check-in: 2:00–3:00 PM | Check-out: 12:00 PM", "Sneak-in child has NO bed and breakfast", "Rates subject to change without prior notice"],
  },
  {
    name: "Bantayan", slug: "bantayan", tagline: "Pristine island escape in Cebu",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&q=80&fit=crop",
    hero: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1400&q=90&fit=crop",
    package: "3D2N Bantayan Land Arrangement",
    hotelCategories: [
      { label: "Budget", hotels: "Arnold's Hotel, Anaya Beach Resort, Coucou Lodge (no breakfast)", rates: [{ label: "5 Pax", price: "₱3,499/person" }, { label: "Quad Share", price: "₱4,299/person" }, { label: "Triple Share", price: "₱5,499/person" }, { label: "Twin Share", price: "₱6,799/person" }, { label: "Solo", price: "₱12,499" }, { label: "Sneak-in Child (0–9 yrs)", price: "₱3,199" }] },
      { label: "Standard A", hotels: "Ahava Boutique Hotel (no breakfast)", rates: [{ label: "5 Pax", price: "₱4,599/person" }, { label: "Quad Share", price: "₱5,499/person" }, { label: "Triple Share", price: "₱5,999/person" }, { label: "Twin Share", price: "₱7,099/person" }, { label: "Solo", price: "₱13,499" }, { label: "Sneak-in Child (0–9 yrs)", price: "₱3,199" }] },
      { label: "Standard B", hotels: "The Coral Blue Oriental, Teza Resort, Jelly Haven Resort, Anika Island Resort", rates: [{ label: "Quad Share", price: "₱6,899/person" }, { label: "Triple Share", price: "₱8,199/person" }, { label: "Twin Share", price: "₱10,599/person" }, { label: "Solo", price: "₱20,499" }, { label: "Sneak-in Child (0–9 yrs)", price: "₱3,199" }] },
    ],
    inclusions: ["3D2N Hotel Accommodation", "Daily Hotel Breakfast", "Round Trip Airport Transfers (Shared Van)"],
    exclusions: ["Round-trip Airfare", "Other Meals and Personal Expenses", "Hotel Security Deposit", "Ferry Ticket Hagnaya to Sta. Fe: ₱385/way", "Ecological Fee: ₱100/way", "Terminal Fee: ₱25/way"],
    itinerary: [
      { day: "Day 1", title: "Arrival", details: "Arrival at Mactan Airport. Transfer to Hagnaya Port (3–5 hrs), ferry to Sta. Fe Port (1 hr), transfer to hotel. Overnight." },
      { day: "Day 2", title: "Free Time", details: "Breakfast. Free time or optional tours." },
      { day: "Day 3", title: "Departure", details: "Breakfast. Free time or optional tours. Check-out. Transfer to airport." },
    ],
    notes: ["Private Airport Transfer: Add ₱8,000/van/RT", "Hotel check-in: 2:00–3:00 PM | Check-out: 12:00 PM"],
  },
  {
    name: "Batanes", slug: "batanes", tagline: "The rugged beauty of the northernmost isles",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80&fit=crop",
    hero: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1400&q=90&fit=crop",
    videoUrl: "https://bit.ly/GDX-BATANES-VID",
    package: "3D2N Batanes Land Arrangement",
    hotelCategories: [
      { label: "Budget", hotels: "Ichehan Lodge Batanes, Casa Feliciano", rates: [{ label: "5 Pax", price: "₱2,199/person" }, { label: "Quad Share", price: "₱2,499/person" }, { label: "Triple Share", price: "₱3,099/person" }, { label: "Twin Share", price: "₱3,399/person" }, { label: "Solo", price: "₱6,099" }, { label: "Sneak-in Child (2–4 yrs)", price: "₱1,200" }] },
      { label: "Standard A", hotels: "Midtown Inn, Hillside Villa", rates: [{ label: "5 Pax", price: "₱2,899/person" }, { label: "Quad Share", price: "₱3,099/person" }, { label: "Triple Share", price: "₱3,399/person" }, { label: "Twin Share", price: "₱3,799/person" }, { label: "Solo", price: "₱6,599" }, { label: "Sneak-in Child (2–4 yrs)", price: "₱1,200" }] },
      { label: "Standard B", hotels: "Boulder-Bay Residences, Villa de Babat, Domingo's Inn, Bernardos Lantia Hotel", rates: [{ label: "5 Pax", price: "₱3,299/person" }, { label: "Quad Share", price: "₱3,499/person" }, { label: "Triple Share", price: "₱3,799/person" }, { label: "Twin Share", price: "₱4,399/person" }, { label: "Solo", price: "₱8,099" }, { label: "Sneak-in Child (2–4 yrs)", price: "₱1,200" }] },
      { label: "4-Star", hotels: "Residencia Du Basco, Batanes Seaside Lodge and Restaurant", rates: [{ label: "5 Pax", price: "₱4,199/person" }, { label: "Quad Share", price: "₱4,499/person" }, { label: "Triple Share", price: "₱4,799/person" }, { label: "Twin Share", price: "₱5,199/person" }, { label: "Solo", price: "₱8,699" }, { label: "Sneak-in Child (2–4 yrs)", price: "₱1,200" }] },
    ],
    inclusions: ["3D2N Hotel Accommodation", "Daily Hotel Breakfast", "Round Trip Airport Transfers"],
    exclusions: ["Round-trip Airfare", "Other Meals and Personal Expenses", "Round-trip Transfer not included for Residencia Du Basco & Bernardos Lantia", "Hotel Security Deposit"],
    itinerary: [
      { day: "Day 1", title: "Arrival", details: "Arrival at Basco Airport. Transfer to hotel. Check-in. Free time. Overnight." },
      { day: "Day 2", title: "Free Time", details: "Breakfast. Free time or optional tours." },
      { day: "Day 3", title: "Departure", details: "Breakfast. Free time. Check-out. Transfer to airport." },
    ],
    notes: ["Bernardos Lantia Hotel: Add ₱1,400 roundtrip airport transfer", "Residencia Du Basco: Add ₱1,400 roundtrip transfer (max 10 pax)", "Hotel check-in: 2:00–3:00 PM | Check-out: 12:00 PM"],
  },
  {
    name: "Bacolod", slug: "bacolod", tagline: "The City of Smiles awaits you",
    image: "https://images.unsplash.com/photo-1483683804023-6ccdb62f86ef?w=1200&q=90&fit=crop",
    hero: "https://images.unsplash.com/photo-1483683804023-6ccdb62f86ef?w=1200&q=90&fit=crop",
    package: "3D2N Bacolod Land Arrangement",
    hotelCategories: [
      { label: "Budget", note: "No Breakfast", hotels: "Ong Bun Pension House, Pension Bacolod", rates: [{ label: "5 Pax", price: "₱2,599/person" }, { label: "Quad Share", price: "₱2,999/person" }, { label: "Triple Share", price: "₱3,499/person" }, { label: "Twin Share", price: "₱3,799/person" }, { label: "Solo", price: "₱6,499" }, { label: "Sneak-in Child (4–9 yrs)", price: "₱2,533" }] },
      { label: "Standard A", hotels: "L'Fisher Ecotel, The Inns by The Oriental Bacolod, Sukro, 11th Street B&B, Suntal Residences", rates: [{ label: "5 Pax", price: "₱3,399/person" }, { label: "Quad Share", price: "₱3,599/person" }, { label: "Triple Share", price: "₱4,399/person" }, { label: "Twin Share", price: "₱4,499/person" }, { label: "Solo", price: "₱8,299" }, { label: "Sneak-in Child (4–9 yrs)", price: "₱2,533" }] },
      { label: "Standard B", hotels: "East View Hotel, Circle Inn, Acacia Hotel, North Tourist Inn", rates: [{ label: "5 Pax", price: "₱3,999/person" }, { label: "Quad Share", price: "₱4,599/person" }, { label: "Triple Share", price: "₱4,899/person" }, { label: "Twin Share", price: "₱6,299/person" }, { label: "Solo", price: "₱10,899" }, { label: "Sneak-in Child (4–9 yrs)", price: "₱2,533" }] },
      { label: "4-Star", hotels: "L'Fisher Main, Stonehills Suites", rates: [{ label: "5 Pax", price: "₱5,999/person" }, { label: "Quad Share", price: "₱6,299/person" }, { label: "Triple Share", price: "₱6,799/person" }, { label: "Twin Share", price: "₱6,899/person" }, { label: "Solo", price: "₱13,099" }, { label: "Sneak-in Child (4–9 yrs)", price: "₱2,533" }] },
    ],
    inclusions: ["3D2N Hotel Accommodation", "Daily Breakfast (except Budget Hotels, Sukro & Suntal Residences)", "Round-trip Transfer (Airport–Hotel–Airport)"],
    exclusions: ["Round-trip Airfare", "Other Meals and Personal Expenses", "Hotel Security Deposit", "Optional Tours"],
    itinerary: [
      { day: "Day 1", title: "Arrival", details: "Arrival at Bacolod-Silay International Airport. Transfer to hotel. Free time. Overnight." },
      { day: "Day 2", title: "Free Time", details: "Breakfast. Free time or optional tours." },
      { day: "Day 3", title: "Departure", details: "Breakfast. Free time. Check-out. Transfer to port for departure." },
    ],
    notes: ["Hotel check-in: 2:00–3:00 PM | Check-out: 12:00 PM", "Rates subject to change without prior notice"],
  },
  {
    name: "Bohol", slug: "bohol", tagline: "Chocolate Hills and tarsier wonders",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=1200&q=90&fit=crop",
    hero: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=1200&q=90&fit=crop",
    videoUrl: "https://bit.ly/GDX-BOHOL-VID",
    package: "3D2N Bohol Land Arrangement",
    hotelCategories: [
      { label: "Budget", hotels: "Cresebo Mansion, Coco Mango's Place, Greenfields Tourist Inn, Ecostay Panglao Resort Hotel", rates: [{ label: "5 Pax", price: "₱2,899/person" }, { label: "Quad Share", price: "₱2,999/person" }, { label: "Triple Share", price: "₱3,199/person" }, { label: "Twin Share", price: "₱3,799/person" }, { label: "Solo", price: "₱6,499" }, { label: "Sneak-in Child (3–5 yrs)", price: "₱1,600" }] },
      { label: "Standard A", hotels: "Marilou Dumaluan Beach Resort, Ananda Resort, Bohol Bee Farm, Positano Alona Beach, Alona Beachside Inn", rates: [{ label: "5 Pax", price: "₱4,199/person" }, { label: "Quad Share", price: "₱4,499/person" }, { label: "Triple Share", price: "₱4,699/person" }, { label: "Twin Share", price: "₱4,899/person" }, { label: "Solo", price: "₱8,699" }, { label: "Sneak-in Child (3–5 yrs)", price: "₱1,600" }] },
      { label: "Standard B", hotels: "Lost Horizon Beach Dive Resort, Alona42 Resort, Panglao Sea Resort, Panglao Pearl White Sand Resort, The Story Resort & Spa, Azahar Resort", rates: [{ label: "5 Pax", price: "₱4,599/person" }, { label: "Quad Share", price: "₱5,199/person" }, { label: "Triple Share", price: "₱5,999/person" }, { label: "Twin Share", price: "₱7,499/person" }, { label: "Solo", price: "₱14,199" }, { label: "Sneak-in Child (3–5 yrs)", price: "₱1,600" }] },
      { label: "4-Star", hotels: "Bluewater Panglao, Bohol Shores, Bohol Beach Club, Panglao Vista Suites", rates: [{ label: "Quad Share", price: "₱5,599/person" }, { label: "Triple Share", price: "₱7,599/person" }, { label: "Twin Share", price: "₱8,599/person" }, { label: "Solo", price: "₱16,499" }, { label: "Sneak-in Child (3–5 yrs)", price: "₱1,600" }] },
      { label: "5-Star", hotels: "Amarela Resort, The Bellevue Resort, Mithi Resort and Spa", rates: [{ label: "Triple Share", price: "₱10,799/person" }, { label: "Twin Share", price: "₱12,699/person" }, { label: "Solo", price: "₱24,699" }, { label: "Sneak-in Child (3–5 yrs)", price: "₱1,600" }] },
    ],
    inclusions: ["3D2N Hotel Accommodation", "Daily Hotel Breakfast", "Round Trip Airport Transfers"],
    exclusions: ["Round-trip Airfare", "Other Meals and Personal Expenses", "Hotel Security Deposit"],
    itinerary: [
      { day: "Day 1", title: "Arrival", details: "Arrival in Panglao, Bohol. Pick up and transfer to resort. Check-in 2:00 PM. Relax. Overnight." },
      { day: "Day 2", title: "Free Time", details: "Breakfast. Free time or optional tours." },
      { day: "Day 3", title: "Departure", details: "Breakfast. Free time or Island Hopping. Check-out. Transfer to airport." },
    ],
    optionalTours: [
      { name: "Bohol Countryside Tour (Joiners)", price: "₱1,449/person | Meet up: McDo Panglao 8:00 AM", details: "Blood Compact, Baclayon Church, Python, Man-made Forest, Tarsiers & Butterfly, Chocolate Hills, Souvenir Shop. Includes: Local Guide, AC Van, Entrance Fees.\nAdd-ons: ATV Rides ₱1,400/person (1hr), Loboc River Cruise ₱1,200/adult, Mirror of the World ₱490/person" },
      { name: "Bohol Island Hopping (Joiners)", price: "₱1,600/person | Meet up: Blue Ocean Resort Alona Beach 6:00 AM", details: "Dolphin Watching, Balicasag Island, Snorkeling at Fish Sanctuary, Turtle Watching, Virgin Island Sandbar. Includes: Boat, Environmental Fee, Licensed Guide, Snorkeling Gears, Life Vest" },
      { name: "Bohol Panglao Package Tour (Exclusive)", price: "2 pax: ₱1,650/person | 3 pax: ₱1,299 | 4–5 pax: ₱1,050", details: "Bohol Bee Farm, Hinagdanan Cave, Dauis Church, Panglao Church, Shell Museum, Moadto Strip" },
    ],
    notes: ["Hotel check-in: 2:00–3:00 PM | Check-out: 12:00 PM", "Rates subject to change without prior notice"],
  },
  {
    name: "Cebu", slug: "cebu", tagline: "Queen City of the South",
    image: "https://images.unsplash.com/photo-1555400038-63f5ba517a47?w=600&q=80&fit=crop",
    hero: "https://images.unsplash.com/photo-1555400038-63f5ba517a47?w=1400&q=90&fit=crop",
    videoUrl: "https://bit.ly/GDX-CEBU-VID",
    package: "3D2N Cebu Land Arrangement",
    hotelCategories: [
      { label: "Budget", hotels: "Metropark Hotel, EON Centennial Soho, Well Hotel, Felicity Island Hotel, Cebu R Hotel Capitol, Kiwi Hotel, Andy Hotel", rates: [{ label: "5 Pax", price: "₱3,399/person" }, { label: "Quad Share", price: "₱4,399/person" }, { label: "Triple Share", price: "₱4,899/person" }, { label: "Twin Share", price: "₱5,399/person" }, { label: "Solo", price: "₱7,799" }, { label: "Sneak-in Child (3–6 yrs)", price: "₱1,900" }] },
      { label: "Standard A", hotels: "Griffin Hotel & Suites, Main Hotel & Suites, Palm Grass The Cebu Heritage, Royal J Hotel, Uncle Tom's Cabin, City Pod Hotel, S Hotel & Residences, Mabolo Royal Hotel", rates: [{ label: "5 Pax", price: "₱4,399/person" }, { label: "Quad Share", price: "₱4,499/person" }, { label: "Triple Share", price: "₱5,099/person" }, { label: "Twin Share", price: "₱5,599/person" }, { label: "Solo", price: "₱8,799" }, { label: "Sneak-in Child (3–6 yrs)", price: "₱1,900" }] },
      { label: "Standard B", hotels: "Citi Park Hotel, Goldberry Suites, Sarrosa International, MJ Hotel & Suites, Golden Prince Hotel, Mezzo Hotel, Bayfront Hotel, Yello Hotel, Quest Hotel, Cebu Parklane, Kojo Hotel, Vivien's Hotel", rates: [{ label: "5 Pax", price: "₱5,699/person" }, { label: "Quad Share", price: "₱5,699/person" }, { label: "Triple Share", price: "₱7,399/person" }, { label: "Twin Share", price: "₱8,299/person" }, { label: "Solo", price: "₱12,799" }, { label: "Sneak-in Child (3–6 yrs)", price: "₱1,900" }] },
      { label: "4-Star", hotels: "Crown Regency Hotel & Towers, Maayo Hotel, The Noble Cebu", rates: [{ label: "Triple Share", price: "₱7,599/person" }, { label: "Twin Share", price: "₱8,599/person" }, { label: "Solo", price: "₱14,999" }, { label: "Sneak-in Child (3–6 yrs)", price: "₱1,900" }] },
      { label: "High-End", hotels: "Seda Central Bloc, Seda Ayala Center, Waterfront Cebu City Hotel & Casino, Blue Water Maribago, Costabella Tropical Beach Hotel", rates: [{ label: "Triple Share", price: "₱10,099/person" }, { label: "Twin Share", price: "₱12,099/person" }, { label: "Solo", price: "₱21,099" }, { label: "Sneak-in Child (3–6 yrs)", price: "₱1,900" }] },
    ],
    inclusions: ["3D2N Hotel Accommodation", "Daily Hotel Breakfast", "Round Trip Airport Transfers", "Complimentary City and Uphill Tour", "Entrance Fees", "Fuel and Parking Fees"],
    exclusions: ["Round-trip Airfare", "Other Meals and Personal Expenses", "Environmental Fees", "Hotel Security Deposit"],
    itinerary: [
      { day: "Day 1", title: "Arrival", details: "Arrival at Mactan Airport. Transfer to hotel for check-in. Free time. Overnight." },
      { day: "Day 2", title: "Cebu City Tour", details: "Breakfast. Complimentary Cebu City Tour (Joiner). Pick up: SM Traveller's Lounge 8:30 AM | Duration: 8 Hours.\n10K Roses • CCLEX • Sirao Flower Farm • Temple of Leah • Taoist Temple • Cebu Heritage Monument • Sto. Nino Church • Magellan's Cross • Shamrock Pasalubong • House of Lechon" },
      { day: "Day 3", title: "Departure", details: "Breakfast. Free time or optional tours. Check-out. Transfer to airport." },
    ],
    optionalTours: [
      { name: "Oslob Whale Shark Tour", price: "₱1,900/person | Pick up: 3:00 AM onwards", details: "Whale Watching/Swimming, Sumilon Island Sandbar, Simala Church, Oslob Cuartel, Carcar Pasalubong. Whale Shark Fee: Local ₱500 | Foreign ₱1,000" },
      { name: "Moalboal Tour", price: "₱1,650/person | Pick up: 4:00 AM onwards", details: "Sardines Tornado Run, Sea Turtle Sanctuary, Lambug Beach, Kawasan Falls, Carcar Pasalubong" },
      { name: "Moalboal with Kawasan Canyoneering", price: "₱3,500/person | Pick up: 4:00 AM | Includes 1 FREE Meal", details: "Sea Turtle Encounter, Swimming with Sardines, Kawasan Falls Canyoneering, Carcar Pasalubong" },
      { name: "Bohol Side Trip (Private)", price: "2 pax: ₱5,018 | 3 pax: ₱4,219 | 4 pax: ₱3,819 | 5 pax: ₱3,722", details: "Blood Compact, Baclayon Church, Python, Loboc River (optional), Man-made Forest, Tarsiers & Butterfly, Chocolate Hills. Includes: Ferry Tickets, Private Van, Entrance Fees" },
    ],
    notes: ["Hotel check-in: 2:00–3:00 PM | Check-out: 12:00 PM", "No tour every 3rd Wednesday of the month"],
  },
  {
    name: "Camiguin", slug: "camiguin", tagline: "Island born of fire, surrounded by sea",
    image: "https://images.unsplash.com/photo-1516690561799-46d8f74f9abf?w=600&q=80&fit=crop",
    hero: "https://images.unsplash.com/photo-1516690561799-46d8f74f9abf?w=1400&q=90&fit=crop",
    videoUrl: "https://bit.ly/GDX-CAMIGUIN-VID",
    package: "3D2N Camiguin Land Arrangement",
    hotelCategories: [
      { label: "Budget", hotels: "Nypa Style Resort, Golden Sunset Beach Club, Havendwell Garden Resort, Havendwell Beach Resort", rates: [{ label: "5 Pax", price: "₱3,199/person" }, { label: "Quad Share", price: "₱3,599/person" }, { label: "Triple Share", price: "₱4,099/person" }, { label: "Twin Share", price: "₱5,099/person" }, { label: "Solo", price: "₱9,299" }, { label: "Sneak-in Child (3–5 yrs)", price: "₱1,899" }] },
      { label: "Standard A", hotels: "Camiguin Volcan Beach Eco Retreat, Agoho Resort, Villa Corales Homestay", rates: [{ label: "Quad Share", price: "₱3,999/person" }, { label: "Triple Share", price: "₱4,699/person" }, { label: "Twin Share", price: "₱5,299/person" }, { label: "Solo", price: "₱9,399" }, { label: "Sneak-in Child (3–5 yrs)", price: "₱1,899" }] },
      { label: "Standard B", hotels: "Paras Beach Resort, Bintana sa Paraiso, Tongatok Cliff, Balai sa Baibai", rates: [{ label: "5 Pax", price: "₱4,499/person" }, { label: "Quad Share", price: "₱4,799/person" }, { label: "Triple Share", price: "₱5,899/person" }, { label: "Twin Share", price: "₱8,699/person" }, { label: "Solo", price: "₱15,999" }, { label: "Sneak-in Child (3–5 yrs)", price: "₱1,899" }] },
      { label: "4-Star", hotels: "Nouveau Hotel", rates: [{ label: "Quad Share", price: "₱16,199/person" }, { label: "Triple Share", price: "₱21,299/person" }, { label: "Twin Share", price: "₱11,099/person" }, { label: "Solo", price: "₱21,499" }, { label: "Sneak-in Child (3–5 yrs)", price: "₱1,899" }] },
    ],
    inclusions: ["3D2N Hotel Accommodation", "Daily Hotel Breakfast", "Roundtrip Airport Transfer"],
    exclusions: ["Round-trip Airfare", "Other Meals and Personal Expenses", "Hotel Security Deposit", "Optional Tours"],
    itinerary: [
      { day: "Day 1", title: "Arrival", details: "Arrival at Mambajao (Camiguin) Airport. Transfer to hotel. Free time. Overnight." },
      { day: "Day 2", title: "Free Time", details: "Breakfast. Free time or optional tours." },
      { day: "Day 3", title: "Departure", details: "Breakfast. Free time. Check-out. Transfer to airport." },
    ],
    notes: ["Camiguin Volcan Beach: Add ₱500/way airport transfer", "Bintana sa Paraiso: Add ₱500/way", "Nouveau Hotel: Add ₱500/way", "Hotel check-in: 2:00–3:00 PM | Check-out: 12:00 PM"],
  },
  {
    name: "Northern Mindanao", slug: "northern-mindanao", tagline: "Gateway to the heart of Mindanao",
    image: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?w=600&q=80&fit=crop",
    hero: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?w=1400&q=90&fit=crop",
    videoUrl: "https://bit.ly/GDX-NORTHERN-MINDANAO-VID",
    package: "5D4N Northern Mindanao Land Arrangement — CDO + Bukidnon + Camiguin",
    hotelCategories: [
      { label: "Budget (Camiguin)", hotels: "Nypa Style Resort, Golden Sunset Beach Club, Havendwell Garden Resort, Havendwell Beach Resort", rates: [{ label: "5 Pax", price: "₱13,599/person" }, { label: "Quad Share", price: "₱16,999/person" }, { label: "Triple Share", price: "₱18,299/person" }, { label: "Twin Share", price: "₱23,399/person" }, { label: "Solo", price: "₱42,299" }] },
      { label: "Standard A (Camiguin)", hotels: "Camiguin Volcan Beach Eco Retreat, Agoho Resort, Villa Corales Homestay", rates: [{ label: "Quad Share", price: "₱17,699/person" }, { label: "Triple Share", price: "₱19,599/person" }, { label: "Twin Share", price: "₱24,699/person" }, { label: "Solo", price: "₱44,499" }] },
      { label: "Standard B (Camiguin)", hotels: "Paras Beach Resort, Bintana sa Paraiso, Tongatok Cliff, Balai sa Baibai", rates: [{ label: "5 Pax", price: "₱15,799/person" }, { label: "Quad Share", price: "₱18,799/person" }, { label: "Triple Share", price: "₱20,899/person" }, { label: "Twin Share", price: "₱28,299/person" }, { label: "Solo", price: "₱52,399" }] },
      { label: "4-Star (Camiguin)", hotels: "Nouveau Hotel", rates: [{ label: "Triple Share", price: "₱40,199/person" }, { label: "Twin Share", price: "₱35,399/person" }, { label: "Solo", price: "₱65,799" }] },
      { label: "CDO Hotels — Budget", hotels: "GC Suites, Marianne Suites, Downtown Suites, Stay CDO Inn", rates: [] },
      { label: "CDO Hotels — Standard A", hotels: "Benrose Hotel, New Dawn Pensionne, Philtown Hotel, Grand City Hotel, Red Planet Hotel CDO", rates: [] },
      { label: "CDO Hotels — Standard B", hotels: "The Upperhouse Hotel, The VIP Hotel, New Dawn Hotel Plus", rates: [] },
      { label: "CDO Hotels — 4-Star", hotels: "Seda Centrio CDO, Limketkai Luxe Hotel", rates: [] },
    ],
    inclusions: ["5D4N Hotel Accommodation", "Daily Hotel Breakfast", "Roundtrip Car/Van Transfer (CDO)", "Airport/Port Transfer", "CDO City/Bukidnon/Camiguin Tour", "Entrance & Environmental Fees", "Boat Fees", "Driver/Guide", "Drone Shots (subject to availability)", "Water Rafting"],
    exclusions: ["Round-trip Airfare", "Other Meals and Personal Expenses", "Ferry Ticket (Balingoan to Benoni Port)", "All rides in Dahilayan", "All rides in Amaya's View", "Snorkeling Fee"],
    itinerary: [
      { day: "Day 1", title: "Arrival + Bukidnon Dahilayan Tour", details: "Arrival at Laguindingan International Airport. Proceed to Bukidnon Dahilayan Tour.\nImpasugong Tourism • Giant Statue • Lovers' Lane • Communal Ranch • Pineapple Marker • Del Monte Plantation • Dahilayan Forest Park & Adventure" },
      { day: "Day 2", title: "CDO City Tour + White Water Rafting", details: "Breakfast. Morning: White Water Rafting. Afternoon: Cathedral Church, Gaston Park, Eden Solace Overview, Amaya View." },
      { day: "Day 3", title: "Transfer to Camiguin", details: "Early check-out. Transfer to Balingoan Port. Arrival Benoni Port Camiguin.\nTongatok Viewpoint • Sunken Cemetery • Old Church Ruins • Walkway to Old Volcano • Tuasan Falls • Sto. Nino Cold Spring • Soda Cold Water" },
      { day: "Day 4", title: "Camiguin Island Tour", details: "Breakfast. Continue Camiguin Tour.\nWhite Island Beach • Mantigue Island • Katunggan Mangrove Park • Katibawasan Falls • Ardent Spring" },
      { day: "Day 5", title: "Departure", details: "Breakfast. Check-out. Transfer to airport for departure." },
    ],
    notes: ["Hotel check-in: 2:00–3:00 PM | Check-out: 12:00 PM", "Rates subject to change without prior notice"],
  },
  {
    name: "Coron", slug: "coron", tagline: "Crystal lagoons and legendary shipwrecks",
    image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=600&q=80&fit=crop",
    hero: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=1400&q=90&fit=crop",
    videoUrl: "https://bit.ly/GDX-CORON-VID",
    package: "3D2N Coron Land Arrangement",
    hotelCategories: [
      { label: "Budget", hotels: "Macky's Hidden Inn, King Michael NCB Homestay, Islands View Inn, Sun Valley Tourist Inn, Jazmine's Place, Divine Castle Travellers Inn, R2R Bayview Inn, Luis Bay Travellers Lodge, Balaibinda Lodge", rates: [{ label: "5 Persons", price: "₱2,899/person" }, { label: "Quad Share", price: "₱3,599/person" }, { label: "Triple Share", price: "₱3,799/person" }, { label: "Solo", price: "₱6,599" }, { label: "Sneak-in Child (3–6 yrs)", price: "₱1,700" }] },
      { label: "Standard A", hotels: "The Ridge Coron, Acacia Garden Inn, The Bay Area, Island Wanderers Inn, Casa Montemar B&B, Mountain View Garden Inn", rates: [{ label: "5 Persons", price: "₱3,399/person" }, { label: "Quad Share", price: "₱3,699/person" }, { label: "Triple Share", price: "₱4,599/person" }, { label: "Solo", price: "₱8,999" }, { label: "Sneak-in Child (3–6 yrs)", price: "₱1,700" }] },
      { label: "Standard B", hotels: "Sunz En Coron, Bluewave Coron, Vienna Hotel, Vela Terraces, Coron Underwater Garden Resort, Kokosnuss Garden Resort, Venus Royale Hotel, Coron Gateway Hotel, Sky Garden Hotel, MO2 Lagoon Coron", rates: [{ label: "5 Persons", price: "₱4,899/person" }, { label: "Quad Share", price: "₱5,099/person" }, { label: "Triple Share", price: "₱5,799/person" }, { label: "Solo", price: "₱11,799" }, { label: "Sneak-in Child (3–6 yrs)", price: "₱1,700" }] },
      { label: "4-Star", hotels: "Coron Westown Resort, Charms Hotel, Corto Del Mar Hotel, Coron Soleil Garden Resort, Asia Grand View Hotel, TAG Resort", rates: [{ label: "Quad Share", price: "₱5,799/person" }, { label: "Triple Share", price: "₱6,799/person" }, { label: "Solo", price: "₱14,399" }, { label: "Sneak-in Child (3–6 yrs)", price: "₱1,700" }] },
      { label: "High-End", hotels: "Zuri Resort, Two Seasons Coron Bayside Hotel", rates: [{ label: "5 Persons", price: "₱6,499/person" }, { label: "Quad Share", price: "₱6,699/person" }, { label: "Triple Share", price: "₱8,099/person" }, { label: "Solo", price: "₱15,999" }, { label: "Sneak-in Child (3–6 yrs)", price: "₱1,700" }] },
      { label: "Paolyn Houseboats", hotels: "Paolyn Houseboats", rates: [{ label: "5 Persons", price: "₱11,199/person" }, { label: "Quad Share", price: "₱14,099/person" }, { label: "Triple Share", price: "₱11,499/person" }, { label: "Solo", price: "₱45,999" }, { label: "Child 3+ yrs", price: "Considered as adult" }] },
    ],
    inclusions: ["3D2N Hotel Accommodation", "Daily Hotel Breakfast", "Round Trip Airport Transfers", "Hotel Taxes and Surcharges"],
    exclusions: ["Round-trip Airfare", "Environmental Fee", "Hotel Security Deposit"],
    itinerary: [
      { day: "Day 1", title: "Arrival", details: "Arrival. Meet and greet. Transfer to hotel. Check-in. Overnight." },
      { day: "Day 2", title: "Free Time / Optional Tours", details: "Breakfast. Free time or optional tours." },
      { day: "Day 3", title: "Departure", details: "Breakfast. Free time and shopping. Check-out. Transfer to airport." },
    ],
    optionalTours: [
      { name: "Coron Town Tour", price: "₱800/person | 3:00 PM–8:00 PM", details: "Mt. Tapyas, Maquinit Hotspring, St. Augustine Church, Lualhati Park, Cashew Factory. Includes: Snacks, Water, Van, Tour Guide, Entrance Fees" },
      { name: "Tour A — Coron Island Tour", price: "₱1,100/person | 9:00 AM–4:30 PM", details: "Kayangan Lake, CYC Beach, Coral Garden, Demanlet, Quin Reef" },
      { name: "Tour B — Coron Island Tour", price: "₱1,300/person | 8:30 AM–4:30 PM", details: "Barracuda Lake, Banul Beach, Balinsasayaw, Twin Lagoon, Reef Garden" },
      { name: "Escapade Tour", price: "₱1,500/person | 9:00 AM–5:00 PM", details: "Malcapuya Island, Banana Island, Bulog Dos Beach" },
      { name: "Reef & Wrecks", price: "₱1,500/person | 8:30 AM–5:00 PM", details: "Pass Island, Lusong Gunboat, Lusong Coral Garden, East Tangat Wreck" },
      { name: "Coron Island Ultimate Tour", price: "₱1,500/person | 9:00 AM–4:30 PM", details: "Kayangan Lake, Lake Atwayan Beach, Coral Garden, CYC Beach, Twin Lagoon, Balinsasayaw" },
      { name: "Calauit Safari", price: "₱2,550/person | 7:30 AM–6:00 PM (lunch included)", details: "Calauit Safari Park, Black Island, Coral Garden, Busuanga Town, Buluang Fishpond" },
      { name: "Coron Island Super Ultimate", price: "₱1,700/person | 9:00 AM–5:00 PM", details: "Barracuda Lake, Kayangan Lake, Atwayan Beach, Coral Garden, Balinsasayaw, Siete Picados, Twin Lagoon, CYC Beach" },
    ],
    notes: ["At least 1 tour is mandatory per protocol", "Environmental Fee: ₱200/person", "Hotel check-in: 2:00–3:00 PM | Check-out: 12:00 PM"],
  },
  {
    name: "Cagayan de Oro", slug: "cagayan-de-oro", tagline: "The City of Golden Friendship",
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&q=80&fit=crop",
    hero: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1400&q=90&fit=crop",
    videoUrl: "https://bit.ly/GDX-CDO-VID",
    package: "3D2N Cagayan de Oro Land Arrangement",
    hotelCategories: [
      { label: "Budget", hotels: "GC Suites, Marianne Suites, Downtown Suites, Stay CDO Inn (no breakfast)", rates: [{ label: "5 Pax", price: "₱3,199/person" }, { label: "Quad Share", price: "₱3,999/person" }, { label: "Triple Share", price: "₱4,499/person" }, { label: "Twin Share", price: "₱5,299/person" }, { label: "Solo", price: "₱7,699" }] },
      { label: "Standard A", hotels: "Benrose Hotel, New Dawn Pensionne, Philtown Hotel, Grand City Hotel, Red Planet Hotel CDO", rates: [{ label: "5 Pax", price: "₱3,699/person" }, { label: "Quad Share", price: "₱4,399/person" }, { label: "Triple Share", price: "₱5,099/person" }, { label: "Twin Share", price: "₱6,399/person" }, { label: "Solo", price: "₱9,799" }] },
      { label: "Standard B", hotels: "The Upperhouse Hotel, The VIP Hotel, New Dawn Hotel Plus", rates: [{ label: "5 Pax", price: "₱3,999/person" }, { label: "Quad Share", price: "₱4,599/person" }, { label: "Triple Share", price: "₱5,299/person" }, { label: "Twin Share", price: "₱6,599/person" }, { label: "Solo", price: "₱11,099" }] },
      { label: "4-Star", hotels: "Seda Centrio CDO, Limketkai Luxe Hotel", rates: [{ label: "Triple Share", price: "₱9,099/person" }, { label: "Twin Share", price: "₱11,099/person" }, { label: "Solo", price: "₱18,699" }] },
    ],
    inclusions: ["3D2N Hotel Accommodation", "Daily Hotel Breakfast (except Stay CDO Inn)", "Roundtrip Airport Transfer"],
    exclusions: ["Round-trip Airfare", "Meals and Personal Expenses", "Hotel Security Deposit", "Optional Tours"],
    itinerary: [
      { day: "Day 1", title: "Arrival", details: "Arrival at Laguindingan International Airport. Transfer to hotel. Free time. Overnight." },
      { day: "Day 2", title: "Free Time", details: "Breakfast. Free time or optional tours." },
      { day: "Day 3", title: "Departure", details: "Breakfast. Free time. Check-out. Transfer to airport." },
    ],
    notes: ["Hotel check-in: 2:00–3:00 PM | Check-out: 12:00 PM", "Rates subject to change without prior notice"],
  },
  {
    name: "Davao", slug: "davao", tagline: "The King City of the South",
    image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=600&q=80&fit=crop",
    hero: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1400&q=90&fit=crop",
    videoUrl: "https://bit.ly/GDX-DAVAO-VID",
    package: "3D2N Davao Land Arrangement",
    hotelCategories: [
      { label: "Budget", hotels: "Hotel Midori (no breakfast)", rates: [{ label: "5 Pax", price: "₱2,599/person" }, { label: "Quad Share", price: "₱2,899/person" }, { label: "Triple Share", price: "₱3,499/person" }, { label: "Twin Share", price: "₱4,299/person" }, { label: "Solo", price: "₱7,899" }, { label: "Sneak-in Child (3–4 yrs)", price: "₱2,270" }] },
      { label: "Standard A", hotels: "Sumo Asia Hotel, Rogen Inn, Hotel Esse, Red Planet Hotels Davao, Alu Hotel", rates: [{ label: "5 Pax", price: "₱3,999/person" }, { label: "Quad Share", price: "₱3,799/person" }, { label: "Triple Share", price: "₱4,599/person" }, { label: "Twin Share", price: "₱5,499/person" }, { label: "Solo", price: "₱10,199" }, { label: "Sneak-in Child (3–4 yrs)", price: "₱2,270" }] },
      { label: "Standard B", hotels: "Microtel by Wyndham Davao, The Royal Mandaya, Blue Lotus Hotel, Tropika Hotel", rates: [{ label: "Quad Share", price: "₱5,999/person" }, { label: "Triple Share", price: "₱5,999/person" }, { label: "Twin Share", price: "₱6,999/person" }, { label: "Solo", price: "₱12,499" }, { label: "Sneak-in Child (3–4 yrs)", price: "₱2,270" }] },
      { label: "4-Star", hotels: "Waterfront Insular Hotel Davao, Grand Regal Hotel, Acacia Hotel", rates: [{ label: "5 Pax", price: "₱7,199/person" }, { label: "Quad Share", price: "₱7,899/person" }, { label: "Triple Share", price: "₱7,999/person" }, { label: "Twin Share", price: "₱8,699/person" }, { label: "Solo", price: "₱15,199" }, { label: "Sneak-in Child (3–4 yrs)", price: "₱2,270" }] },
      { label: "5-Star", hotels: "Discovery Samal", rates: [{ label: "Triple Share", price: "₱14,199/person" }, { label: "Twin Share", price: "₱16,799/person" }, { label: "Solo", price: "₱32,899" }, { label: "Sneak-in Child (3–4 yrs)", price: "₱2,270" }] },
      { label: "High-End", hotels: "Pearl Farm Beach Resort", rates: [{ label: "5 Pax", price: "₱36,999/person" }, { label: "Quad Share", price: "₱32,799/person" }, { label: "Triple Share", price: "₱26,099/person" }, { label: "Twin Share", price: "₱28,699/person" }, { label: "Solo", price: "₱56,699" }] },
    ],
    inclusions: ["3D2N Hotel Accommodation", "Daily Hotel Breakfast", "Round Trip Airport Transfers"],
    exclusions: ["Round-trip Airfare", "Other Meals and Personal Expenses", "Hotel Security Deposit", "Optional Tours"],
    itinerary: [
      { day: "Day 1", title: "Arrival", details: "Arrival at Francisco Bangoy International Airport. Meet and greet." },
      { day: "Day 2", title: "Free Time / Optional Tours", details: "Breakfast. Free time or optional tours." },
      { day: "Day 3", title: "Departure", details: "Breakfast. Check-out. Transfer to airport." },
    ],
    optionalTours: [
      { name: "Bansalan-Kapatagan", price: "₱4,340/person (min 2) | 5:00 AM–4:00 PM", details: "Cactus Farm, Sky Garden, Twin View Mountain Resort, Temple of Thailand, Montefrio, Jardin de Senorita, Camp Sabros" },
      { name: "Buda-Marilog", price: "₱4,700/person (min 2) | 4:00 AM departure", details: "Sonnen Berg, Hillsview Mountain Resort, Bemwa Garden, Seagull Resort, Highway 81, Buda Vista, Philippine Eagle Statue" },
      { name: "Samal Island Hopping", price: "₱2,399/person | Sat & Sun only | 7:00 AM–4:00 PM (lunch included)", details: "Coral Garden, Dayang Beach, Sabang Cliff/Quidopong Sand Bar, Wishing Island, Sightseeing Pearl Farm, Malipano Island" },
      { name: "Bukidnon-Dahilayan", price: "₱13,950/person (min 2) | 1:00 AM departure", details: "Camp Phillips, Dahilayan Adventure Park, Dahilayan Forest Park, Monastery of Transfiguration, Nature's Overview Bukidnon" },
    ],
    notes: ["Pearl Farm boat: In 10:00 AM / 2:00 PM | Out 8:30 AM / 1:00 PM", "Hotel check-in: 2:00–3:00 PM | Check-out: 12:00 PM"],
  },
  {
    name: "Dinagat", slug: "dinagat", tagline: "Untouched island beauty",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=90&fit=crop",
    hero: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=90&fit=crop",
    videoUrl: "https://bit.ly/GDX-DINAGAT-VID",
    package: "4D3N Dinagat Island Land Arrangement",
    hotelCategories: [
      { label: "Budget", hotels: "Airconditioned with Private CR", rates: [{ label: "5 Pax", price: "₱7,199/person" }, { label: "Quad Share", price: "₱8,799/person" }, { label: "Triple Share", price: "₱9,299/person" }, { label: "Twin Share", price: "₱10,399/person" }, { label: "Solo", price: "₱16,799" }, { label: "Child 3 yrs below", price: "FREE" }, { label: "Child 4–10 yrs", price: "Half Payment" }, { label: "Child 11+ yrs", price: "Full Payment" }] },
    ],
    inclusions: ["4D3N Hotel Accommodation (Airconditioned with Private CR)", "Round Trip Airport Transfers", "Round Trip Fast Craft (Surigao–Dinagat)", "Chartered Boat for Island Hopping", "All Entrance, Environmental, Tour Guide and Docking Fees", "Day 2: Breakfast, Lunch, and Dinner", "Day 3: Breakfast and Lunch", "Day 4: Breakfast", "Cottage Fees"],
    exclusions: ["Round-trip Airfare", "Accommodation Upgrade (Vines Resort): +₱1,000/person/night", "Personal Expenses", "Cave Fee: ₱50/person", "Overlooking Fee at Blue Lagoon: ₱30/person"],
    itinerary: [
      { day: "Day 1", title: "Arrival", details: "Arrival at Surigao Airport. Transfer to accommodation. Check-in. Overnight." },
      { day: "Day 2", title: "Island Tour 8:00 AM–5:00 PM", details: "Hagakhak Rock Formation • Miracle Pool Underground Cave • Jelmars Islet Resort • Blue Lagoon" },
      { day: "Day 3", title: "Island Tour 8:00 AM–5:00 PM", details: "Cabacungan Cove • Duyos Camping Resort • Bitaog Beach • Pagkawasan Garden Resort" },
      { day: "Day 4", title: "Departure", details: "Breakfast. Check-out. Transfer to San Jose Port, boat to Boulevard Surigao, van to Surigao Airport." },
    ],
    notes: ["Boat schedule Surigao to Dinagat: 1:30 PM / 2:15 PM / 3:00 PM / 4:00 PM / 6:15 PM", "Boat schedule Dinagat to Surigao: 8:30 AM / 10:15 AM / 11:30 AM / 12:25 PM / 1:30 PM"],
  },
  {
    name: "Catanduanes", slug: "catanduanes", tagline: "The happy island of the Pacific",
    image: "https://images.unsplash.com/photo-1505118380757-91f5f5632de0?w=600&q=80&fit=crop",
    hero: "https://images.unsplash.com/photo-1505118380757-91f5f5632de0?w=1400&q=90&fit=crop",
    package: "3D2N Catanduanes Land Arrangement",
    hotelCategories: [
      { label: "Budget", hotels: "Lucky Hotel and Resort", rates: [{ label: "10 Pax", price: "₱4,999/person" }, { label: "9 Pax", price: "₱5,299/person" }, { label: "8 Pax", price: "₱5,499/person" }, { label: "7 Pax", price: "₱5,799/person" }, { label: "6 Pax", price: "₱6,099/person" }, { label: "5 Pax", price: "₱6,299/person" }, { label: "4 Pax", price: "₱6,599/person" }, { label: "3 Pax", price: "₱7,999/person" }, { label: "2 Pax", price: "₱9,499/person" }, { label: "Solo", price: "₱16,899" }, { label: "Child 5 yrs below", price: "FREE" }, { label: "Child 6 yrs+", price: "Full Payment" }] },
    ],
    inclusions: ["3D2N Hotel Accommodation", "Complimentary Breakfast", "Roundtrip Airport Transfer", "AC Vehicle during Tour", "All Entrance and Environmental Fees", "Local Guide Fee (Binurong)", "2 Bottled Water per person", "Lunch for Day 1 & 2", "Catanduanes West Tour + East Tour"],
    exclusions: ["Round-trip Airfare", "Travel Insurance", "Anything not in the inclusions"],
    itinerary: [
      { day: "Day 1", title: "West Tour", details: "Arrival • Miraculous Batong Paloway (Our Lady of Sorrow Shrine) • Historical Luyang Cave • Museo de Catanduanes • Virac Cathedral • Twin Rock Beach Resort • Tampad Beach (Face of Jesus Rock) • Fleur de Lilies Glamping Farm • Batag Beach • Mamangal Beach" },
      { day: "Day 2", title: "East Tour", details: "Binurong Point 'Mala Batanes' • Puraran Beach (Surfing Spot) • Batalay Shrine • Bato Church (Oldest in Catanduanes) • Maribina Falls • Implings Latik • Happy Island Marker & Pasalubong Center" },
      { day: "Day 3", title: "Departure", details: "Transfer to Airport." },
    ],
    notes: ["8 hours tour duration every day", "Itinerary may change based on local conditions"],
  },
  {
    name: "Bukidnon", slug: "bukidnon", tagline: "The highland paradise of Mindanao",
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&q=80&fit=crop",
    hero: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1400&q=90&fit=crop",
    videoUrl: "https://bit.ly/GDX-BUKIDNON-VID",
    package: "3D2N Bukidnon Land Arrangement",
    hotelCategories: [
      { label: "Budget", hotels: "Pineapple Dreams Travellers Inn", rates: [{ label: "10 Pax", price: "₱5,799/person" }, { label: "9 Pax", price: "₱6,299/person" }, { label: "8 Pax", price: "₱6,699/person" }, { label: "7 Pax", price: "₱6,999/person" }, { label: "6 Pax", price: "₱7,499/person" }, { label: "5 Pax", price: "₱8,499/person" }, { label: "4 Pax", price: "₱9,499/person" }, { label: "3 Pax", price: "₱10,599/person" }, { label: "2 Pax", price: "₱11,699/person" }, { label: "Solo", price: "₱16,699" }, { label: "Child 4 yrs below", price: "FREE" }, { label: "Child 5 yrs+", price: "Full Payment" }] },
    ],
    inclusions: ["3D2N Hotel Accommodation", "Roundtrip Airport Transfer", "3 Days Tour with Exclusive Transport", "All Entrance, Environmental & Parking Fees", "Driver/Guide & Fuel", "Drone Shots (subject to availability)", "FREE Souvenirs"],
    exclusions: ["Round-trip Airfare", "Travel Insurance", "Food/Meals", "Rides in Dahilayan", "Horseback in Communal Ranch", "Guide fee in Waterfall trek at CEDAR", "Rotypeaks transport and entrances (₱1,200/person)"],
    itinerary: [
      { day: "Day 1", title: "Dahilayan Tour", details: "6:00 AM Pick up at Laguindingan Airport\n9:00 AM Camp Phillips, Pineapple Plantation\n9:30 AM Dahilayan Adventure Park\n1:00 PM Dahilayan Forest Park\n3:00 PM Dahilayan Alpine Village\n4:00 PM Antonio's Cafe\n5:00 PM Drop off at hotel" },
      { day: "Day 2", title: "Impasug-ong Tour", details: "7:30 AM Pick up at hotel\n9:00 AM Panika Head Dress, Municipal Tourism\n9:30 AM Communal Ranch & Lovers Lane\n3:00 PM CEDAR\n5:00 PM Drop off at hotel" },
      { day: "Day 3", title: "Libona–CDO Tour", details: "8:30 AM Pick up at hotel\n9:30 AM Chelly's Restaurant\n10:30 AM Vista West Cafe\n1:00 PM Kinawe Blooming Farm\n2:00 PM Vjandep Pasalubong\n4:00 PM Drop off at Airport/CDO" },
    ],
    notes: ["Itinerary subject to change without notice", "Hotel check-in: 2:00–3:00 PM | Check-out: 12:00 PM"],
  },
  {
    name: "Leyte", slug: "leyte", tagline: "Historic shores and lush landscapes",
    image: "https://images.unsplash.com/photo-1519046904884-53103b34b206?w=600&q=80&fit=crop",
    hero: "https://images.unsplash.com/photo-1519046904884-53103b34b206?w=1400&q=90&fit=crop",
    package: "Leyte — Kalanggaman Island (2 Days 1 Night)",
    hotelCategories: [
      { label: "Rates by Group Size", hotels: "", rates: [{ label: "12 Pax", price: "₱3,999/person" }, { label: "11 Pax", price: "₱4,099/person" }, { label: "10 Pax", price: "₱4,299/person" }, { label: "9 Pax", price: "₱4,399/person" }, { label: "8 Pax", price: "₱4,599/person" }, { label: "7 Pax", price: "₱4,899/person" }, { label: "6 Pax", price: "₱5,199/person" }, { label: "5 Pax", price: "₱5,699/person" }, { label: "4 Pax", price: "₱6,599/person" }, { label: "3 Pax", price: "₱8,099/person" }, { label: "2 Pax", price: "₱11,099/person" }, { label: "Child 1–6 yrs", price: "FREE (sharing food at mainland)" }, { label: "Child 7–11 yrs", price: "₱1,420" }, { label: "Child 12–17 yrs", price: "Less ₱100 from rate" }] },
    ],
    inclusions: ["Airport Pick up and Drop Off", "Private Boat Roundtrip", "Cottage, Table & Chairs", "Buffet or Boodle Fight Lunch", "Dinner, Breakfast + Lunch 2nd Day (Mainland)", "Fruits, Drinking Soda, Bottled Water", "Agency Guide / Food Handler", "Ref Magnet Souvenir", "Free Use of Camping Tent"],
    exclusions: ["Round-trip Airfare", "Other Meals", "Entrance Fee: ₱450 (Filipino)", "Entrance Fee: ₱1,500 (Non-Filipino)", "Speed Boat Upgrade: +₱4,000 (max 10 pax)"],
    itinerary: [
      { day: "Day 1", title: "Kalanggaman Island", details: "7:00 AM Pick up at Tacloban City Airport/Hotel\n8:00 AM Pick up at Ormoc City Airport/Hotel\n10:00 AM Arrival at Tourism 2 Office\n10:30–11:00 AM Depart to Kalanggaman Island\n12:00 PM Lunch served. Stay overnight on island." },
      { day: "Day 2", title: "Departure", details: "7:00 AM Breakfast\n9:00–10:00 AM Pick up back to mainland\n10:30–11:00 AM Arrival mainland, lunch\nAirport/Hotel Drop Off" },
    ],
    optionalTours: [{ name: "Lechon Belly 4kg", price: "₱2,900" }, { name: "Whole Lechon", price: "Available for order" }],
    notes: ["2–4 pax: Bilao set up | 5 pax up: Buffet/Boodle Fight", "Free Lechon Belly for 25 pax and up", "Free Small Lechon for 50 adult pax and up"],
  },
  {
    name: "Port Barton", slug: "port-barton", tagline: "Palawan's hidden cinematic gem",
    image: "https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?w=600&q=80&fit=crop",
    hero: "https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?w=1400&q=90&fit=crop",
    videoUrl: "https://bit.ly/GDX-PORT-BARTON-VID",
    package: "3D2N Port Barton Land Arrangement",
    hotelCategories: [
      { label: "Budget", hotels: "Ausan Beach Front Cottages, JBR Tourist Inn (no breakfast), Forest Wood Suites, Rabang Travellers Inn, Pisces Tourist Inn", rates: [{ label: "5 Pax", price: "₱4,599/person" }, { label: "Quad Share", price: "₱5,699/person" }, { label: "Triple Share", price: "₱7,299/person" }, { label: "Twin Share", price: "₱8,999/person" }, { label: "Solo", price: "₱17,199" }, { label: "Sneak-in Child (3–5 yrs)", price: "₱4,867" }] },
      { label: "Standard A", hotels: "Summer Homes Beach Resort", rates: [{ label: "5 Pax", price: "₱5,199/person" }, { label: "Quad Share", price: "₱6,299/person" }, { label: "Triple Share", price: "₱7,099/person" }, { label: "Twin Share", price: "₱9,399/person" }, { label: "Solo", price: "₱18,099" }, { label: "Sneak-in Child (3–5 yrs)", price: "₱4,867" }] },
      { label: "Standard B", hotels: "Parrots Boutique Resort, Holiday Suites Port Barton, Oasis Port Barton", rates: [{ label: "5 Pax", price: "₱6,999/person" }, { label: "Quad Share", price: "₱8,599/person" }, { label: "Triple Share", price: "₱10,899/person" }, { label: "Twin Share", price: "₱12,099/person" }, { label: "Solo", price: "₱23,499" }, { label: "Sneak-in Child (3–5 yrs)", price: "₱4,867" }] },
    ],
    inclusions: ["3D2N Hotel Accommodation", "Daily Hotel Breakfast", "Roundtrip Airport Transfer"],
    exclusions: ["Round-trip Airfare", "Other Meals and Personal Expenses", "Hotel Security Deposit", "Optional Tours"],
    itinerary: [
      { day: "Day 1", title: "Arrival", details: "Arrival at PPS Airport. Transfer to hotel. Free time. Overnight." },
      { day: "Day 2", title: "Free Time / Optional Tours", details: "Breakfast. Free time or optional tours." },
      { day: "Day 3", title: "Departure", details: "Breakfast. Free time. Check-out. Transfer to airport." },
    ],
    optionalTours: [
      { name: "Tour A Island Hopping", price: "₱1,699/person | Pick up: 8:30–9:00 AM", details: "Twin Reef, Exotic/Maxima Island, Turtle Spot, Fantastic Reef, Starfish Sandbar, Paradise. Includes: Lunch, Boat, Guide, Life Vest, Environmental Fee" },
      { name: "Tour B Island Hopping", price: "₱1,699/person", details: "Paradise Island, Pamuayan Beach, Middle Rock Reef, Blackstone Reef, Bulalacao Reef, Giligan's Reef" },
      { name: "Tour C Island Hopping", price: "₱1,699/person", details: "White Beach, Aquarium Reef, Turtle Spot, Wide Reef, Small Lagoon Reef/Capsalay Island" },
      { name: "Combi Tour", price: "₱1,799/person | 9:00 AM–4:00 PM", details: "Pamuayan Falls & Giligan's, Coconut Beach & White Beach" },
      { name: "Inland Tour", price: "₱1,899/person | 8:30 AM–4:00 PM", details: "Long Beach, Bato Nining, San Vicente View Point" },
    ],
    notes: ["Hotel check-in: 2:00–3:00 PM | Check-out: 12:00 PM", "Rates subject to change without prior notice"],
  },
  {
    name: "Legazpi", slug: "legazpi", tagline: "In the shadow of Mayon Volcano",
    image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=600&q=80&fit=crop",
    hero: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1400&q=90&fit=crop",
    package: "3D2N Legazpi Land Arrangement",
    hotelCategories: [
      { label: "Budget", hotels: "Aurelle Inn, Thirdy Tourist Inn, Casita De Gloria Hometel", rates: [{ label: "5 Pax", price: "₱3,499/person" }, { label: "Quad Share", price: "₱3,599/person" }, { label: "Triple Share", price: "₱4,099/person" }, { label: "Twin Share", price: "₱4,399/person" }, { label: "Solo", price: "₱7,999" }, { label: "Sneak-in Child (6–12 yrs)", price: "₱1,869" }] },
      { label: "Standard A", hotels: "The Applepeach House, Casa Simeon, Casa Roces, Casa Bicolandia", rates: [{ label: "5 Pax", price: "₱3,799/person" }, { label: "Quad Share", price: "₱4,199/person" }, { label: "Triple Share", price: "₱5,399/person" }, { label: "Twin Share", price: "₱5,399/person" }, { label: "Solo", price: "₱10,099" }, { label: "Sneak-in Child (6–12 yrs)", price: "₱1,869" }] },
      { label: "Standard B", hotels: "The Marison Hotel, Hotel Inigo", rates: [{ label: "Triple Share", price: "₱6,199/person" }, { label: "Twin Share", price: "₱6,899/person" }, { label: "Solo", price: "₱12,999" }, { label: "Sneak-in Child (6–12 yrs)", price: "₱1,869" }] },
      { label: "4-Star", hotels: "Hotel St. Ellis, The Oriental Hotels and Resorts", rates: [{ label: "Triple Share", price: "₱7,299/person" }, { label: "Twin Share", price: "₱8,399/person" }, { label: "Solo", price: "₱16,099" }, { label: "Sneak-in Child (6–12 yrs)", price: "₱1,869" }] },
      { label: "5-Star", hotels: "Misibis Bay Cagraray Island", rates: [{ label: "Quad Share", price: "₱10,099/person" }, { label: "Triple Share", price: "₱10,499/person" }, { label: "Twin Share", price: "₱12,699/person" }, { label: "Solo", price: "₱24,699" }, { label: "Sneak-in Child (6–12 yrs)", price: "₱1,869" }] },
    ],
    inclusions: ["3D2N Hotel Accommodation", "Daily Hotel Breakfast", "Round Trip Airport Transfers"],
    exclusions: ["Round-trip Airfare", "Other Meals and Personal Expenses", "Hotel Security Deposit", "Optional Tours"],
    itinerary: [
      { day: "Day 1", title: "Arrival", details: "Arrival at Bicol International Airport. Transfer to hotel. Check-in. Free time. Overnight." },
      { day: "Day 2", title: "Free Time / Optional Tours", details: "Breakfast. Free time or optional tours." },
      { day: "Day 3", title: "Departure", details: "Breakfast. Check-out. Transfer to airport." },
    ],
    notes: ["Hotel check-in: 2:00–3:00 PM | Check-out: 12:00 PM", "Rates subject to change without prior notice"],
  },
  {
    name: "Manila", slug: "manila", tagline: "The pearl of the Orient Seas",
    image: "https://images.unsplash.com/photo-1555400038-63f5ba517a47?w=600&q=80&fit=crop",
    hero: "https://images.unsplash.com/photo-1555400038-63f5ba517a47?w=1400&q=90&fit=crop",
    package: "3D2N Manila Land Arrangement",
    hotelCategories: [
      { label: "Budget", hotels: "Hotel Kimberly, Tiara Oriental Hotel, My Space Hotel and Dormitory, The Selah Garden Hotel, Selah Pods Hotel, Selah Lofts Hotel", rates: [{ label: "Triple Share", price: "₱4,599/person" }, { label: "Twin Share", price: "₱5,699/person" }, { label: "Solo", price: "₱10,599" }] },
      { label: "Standard A", hotels: "The St. Giles Hotel, Amelie Hotel Manila, Golden Phoenix Hotel Manila, Citystate Tower Hotel, Sunstar Grand Hotel", rates: [{ label: "Triple Share", price: "₱5,999/person" }, { label: "Twin Share", price: "₱6,499/person" }, { label: "Solo", price: "₱12,299" }] },
      { label: "Standard B", hotels: "Hotel 101 Manila, Herald Suites Polaris, The E Hotel, Y2 Residence Hotel, Bayview Park Hotel, Sequoia Hotel Manila Bay, Berjaya Makati Hotel, Herald Suites Solana, Herald Suites Chino Roces", rates: [{ label: "Triple Share", price: "₱6,699/person" }, { label: "Twin Share", price: "₱7,099/person" }, { label: "Solo", price: "₱13,499" }] },
      { label: "4-Star", hotels: "Rizal Park Hotel, Winford Manila Resort and Casino, Ramada by Wyndham Manila Central, City Garden Grand Hotel, Armada Hotel Manila, Astoria Plaza, Wynwood Hotel Manila", rates: [{ label: "Triple Share", price: "₱7,299/person" }, { label: "Twin Share", price: "₱7,999/person" }, { label: "Solo", price: "₱15,299" }] },
      { label: "5-Star", hotels: "Seda Vertis North, The Alpha Suites, The Manila Hotel, Makati Diamond Residences", rates: [{ label: "Triple Share", price: "₱9,699/person" }, { label: "Twin Share", price: "₱11,299/person" }, { label: "Solo", price: "₱20,699" }] },
    ],
    inclusions: ["3D2N Hotel Accommodation", "Daily Breakfast (except My Space Dormitory)", "Roundtrip Airport Transfer"],
    exclusions: ["Round-trip Airfare", "Other Meals and Personal Expenses", "Hotel Security Deposit"],
    itinerary: [
      { day: "Day 1", title: "Arrival", details: "Arrival at NAIA Airport. Transfer to hotel. Free time. Overnight." },
      { day: "Day 2", title: "Free Time / Optional Tours", details: "Breakfast. Free time or optional tours." },
      { day: "Day 3", title: "Departure", details: "Breakfast. Free time or optional tours. Check-out. Transfer to airport." },
    ],
    notes: ["Hotel check-in: 2:00–3:00 PM | Check-out: 12:00 PM", "Rates subject to change without prior notice"],
  },
  {
    name: "Siargao", slug: "siargao", tagline: "The surfing capital of the Philippines",
    image: "https://images.unsplash.com/photo-1502680390469-be75c86b636f?w=600&q=80&fit=crop",
    hero: "https://images.unsplash.com/photo-1502680390469-be75c86b636f?w=1400&q=90&fit=crop",
    videoUrl: "https://bit.ly/GDX-SIARGAO-VID",
    package: "3D2N Siargao Land Arrangement",
    hotelCategories: [
      { label: "Budget (No Breakfast)", hotels: "Tropic Hostel, Point F Siargao, Malayah Siargao, Haido Ville", rates: [{ label: "5 Pax", price: "₱2,999/person" }, { label: "Quad Share", price: "₱3,299/person" }, { label: "Triple Share", price: "₱3,799/person" }, { label: "Twin Share", price: "₱3,799/person" }, { label: "Solo", price: "₱6,099" }, { label: "Sneak-in Child (3–5 yrs)", price: "₱2,000" }] },
      { label: "Standard A", hotels: "Sunflower Suites (no breakfast), Tres Islas", rates: [{ label: "5 Pax", price: "₱3,199/person" }, { label: "Quad Share", price: "₱3,599/person" }, { label: "Triple Share", price: "₱4,099/person" }, { label: "Twin Share", price: "₱4,699/person" }, { label: "Solo", price: "₱6,999" }, { label: "Sneak-in Child (3–5 yrs)", price: "₱2,000" }] },
      { label: "Standard B", hotels: "Lisuga Siargao Island, Payag Suites (no breakfast), Suyog Spaces Suites (no breakfast), Langojon Jianjoy Resort (no breakfast), Casavia Siargao Hostel (no breakfast)", rates: [{ label: "5 Pax", price: "₱3,999/person" }, { label: "Quad Share", price: "₱4,199/person" }, { label: "Triple Share", price: "₱4,899/person" }, { label: "Twin Share", price: "₱5,799/person" }, { label: "Solo", price: "₱10,099" }, { label: "Sneak-in Child (3–5 yrs)", price: "₱2,000" }] },
      { label: "High-End", hotels: "Jonas & Twins Resort, Ocean 101 Beach Resort, Cherinicole Beach Resort, Patricks on the Beach, Point 303 Cloud 9 Resort", rates: [{ label: "5 Pax", price: "₱4,799/person" }, { label: "Quad Share", price: "₱5,299/person" }, { label: "Triple Share", price: "₱6,199/person" }, { label: "Twin Share", price: "₱6,999/person" }, { label: "Solo", price: "₱12,099" }, { label: "Sneak-in Child (3–5 yrs)", price: "₱2,000" }] },
      { label: "4–5 Star", hotels: "Happiness Beach Resort, Kalipay Resort Siargao (no breakfast), Apsaras Tribe", rates: [{ label: "Quad Share", price: "₱8,299/person" }, { label: "Triple Share", price: "₱9,699/person" }, { label: "Twin Share", price: "₱11,999/person" }, { label: "Solo", price: "₱22,499" }, { label: "Sneak-in Child (3–5 yrs)", price: "₱2,000" }] },
    ],
    inclusions: ["3D2N Hotel Accommodation", "Daily Breakfast (for specific hotels)", "Roundtrip Airport Transfer"],
    exclusions: ["Round-trip Airfare", "Other Meals and Personal Expenses", "Hotel Security Deposit"],
    itinerary: [
      { day: "Day 1", title: "Arrival", details: "Arrival at Sayak Airport. Transfer to hotel. Check-in." },
      { day: "Day 2", title: "Free Time / Optional Tours", details: "Breakfast. Free time or optional tours." },
      { day: "Day 3", title: "Departure", details: "Breakfast. Free time until transfer to airport." },
    ],
    optionalTours: [
      { name: "Island Hopping", price: "₱1,500/person | Pick up: 7:00–8:00 AM | Ends: 3:00–3:30 PM", details: "Naked Island, Daku Island, Guyam Island, Secret Island (low tide). Includes: Hotel transfers, Environmental Fees, Cottage, Guide, Lunch Boodle Fight, Drinks, Drone Shots, Travel Insurance, Free Mermaid Tail & Volleyball" },
      { name: "Sohoton Tour", price: "₱2,600/person | Pick up: 7:00–8:00 AM | Ends: 4:00–4:40 PM", details: "Sohoton Cove, Magkukuob Cove, Jellyfish Sanctuary (Hagukan Cove), Cliff Diving, Tiktikan Lagoon, Tiktikan Lake, Dagatan Lake, Floating Cottage. Includes: Hotel transfers, Fees, Cottage, Guide, Lunch Boodle Fight, Drinks" },
      { name: "Land Tour", price: "₱1,900/person | Pick up: 7:30–8:00 AM | Ends: 4:00 PM", details: "Coconut Road, Coconut Mountain View, Magpupungko Rock Pools, Maasin River, Sugba Lagoon, Secret Beach. Includes: Van, Environmental Fee, Guide, Plated Lunch (₱250 consumable), Drone Shots" },
      { name: "Corregidor + Tri-Island Tour", price: "₱2,499/person | Pick up: 7:00–8:00 AM | Ends: 4:00 PM", details: "Corregidor Island, Naked Island, Daku Island, Guyam Island. Includes: Hotel transfers, Fees, Cottage, Guide, Lunch Boodle Fight, Drinks, Free Mermaid Tail & Volleyball" },
    ],
    notes: ["8 pax and above = considered exclusive", "Hotel check-in: 2:00–3:00 PM | Check-out: 12:00 PM"],
  },
  {
    name: "Samal", slug: "samal", tagline: "Island Garden City of Samal",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&q=80&fit=crop",
    hero: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1400&q=90&fit=crop",
    package: "3D2N Samal Land Arrangement",
    hotelCategories: [
      { label: "Budget", hotels: "Cavanico Il Mare", rates: [{ label: "5 Pax", price: "₱3,899/person" }, { label: "Quad Share", price: "₱4,499/person" }, { label: "Triple Share", price: "₱5,799/person" }, { label: "Twin Share", price: "₱7,199/person" }, { label: "Solo", price: "₱13,699" }, { label: "Sneak-in Child (3–4 yrs)", price: "₱3,599" }] },
      { label: "Standard A", hotels: "Paradise Island Park & Beach Resort (no breakfast), Holiday Oceanview Residences, Haven's Dew Resort", rates: [{ label: "5 Pax", price: "₱5,099/person" }, { label: "Quad Share", price: "₱5,899/person" }, { label: "Triple Share", price: "₱7,499/person" }, { label: "Twin Share", price: "₱9,099/person" }, { label: "Solo", price: "₱17,499" }, { label: "Sneak-in Child (3–4 yrs)", price: "₱3,599" }] },
      { label: "Standard B", hotels: "Chema's by the Sea, Secdea Resort", rates: [{ label: "5 Pax", price: "₱7,399/person" }, { label: "Quad Share", price: "₱8,099/person" }, { label: "Triple Share", price: "₱10,199/person" }, { label: "Twin Share", price: "₱12,799/person" }, { label: "Solo", price: "₱24,799" }, { label: "Sneak-in Child (3–4 yrs)", price: "₱3,599" }] },
      { label: "5-Star", hotels: "Discovery Samal", rates: [{ label: "Triple Share", price: "₱15,499/person" }, { label: "Twin Share", price: "₱18,699/person" }, { label: "Solo", price: "₱36,699" }, { label: "Sneak-in Child (3–4 yrs)", price: "₱3,599" }] },
      { label: "High-End", hotels: "Pearl Farm Beach Resort", rates: [{ label: "5 Pax", price: "₱37,799/person" }, { label: "Quad Share", price: "₱33,799/person" }, { label: "Triple Share", price: "₱27,399/person" }, { label: "Twin Share", price: "₱30,599/person" }, { label: "Solo", price: "₱60,499" }, { label: "Sneak-in Child (3–4 yrs)", price: "₱3,599" }] },
    ],
    inclusions: ["3D2N Hotel Accommodation", "Daily Hotel Breakfast", "Round Trip Airport Transfers", "Ferry Ticket to Samal"],
    exclusions: ["Round-trip Airfare", "Other Meals and Personal Expenses", "Hotel Security Deposit", "Optional Tours"],
    itinerary: [
      { day: "Day 1", title: "Arrival", details: "Arrival at Francisco Bangoy International Airport. Proceed to ferry bound to Samal." },
      { day: "Day 2", title: "Free Time / Optional Tours", details: "Breakfast. Free time or optional tours." },
      { day: "Day 3", title: "Departure", details: "Breakfast. Check-out. Transfer to airport." },
    ],
    notes: ["Discovery Samal — To Samal: 11AM, 12PM, 2PM, 4PM, 6PM, 8PM, 11PM | From Samal: 8AM, 10AM, 11AM, 1PM, 3PM, 5PM, 7PM, 9PM, 10:30PM", "Pearl Farm — In: 10:00 AM or 2:00 PM | Out: 8:30 AM or 1:00 PM"],
  },
  {
    name: "Ilo-Ilo", slug: "ilo-ilo", tagline: "Heritage, culture, and breathtaking coastlines",
    image: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=1200&q=90&fit=crop",
    hero: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=1200&q=90&fit=crop",
    package: "3D2N Ilo-Ilo Land Arrangement",
    hotelCategories: [
      { label: "Budget", hotels: "Harbor Town Hotel, Ferrymar Hotel, Ong Bun Pension House (no breakfast), GT Hotel Iloilo", rates: [{ label: "Quad Share", price: "₱2,899/person" }, { label: "Triple Share", price: "₱3,699/person" }, { label: "Twin Share", price: "₱4,299/person" }, { label: "Solo", price: "₱7,799" }, { label: "Sneak-in Child (3–6 yrs)", price: "₱1,897" }] },
      { label: "Standard A", hotels: "The Grand Dame Hotel, Hotel Del Rio, District 21, Grand Xing Imperial Hotel, Injap Tower Hotel", rates: [{ label: "5 Pax", price: "₱3,399/person" }, { label: "Quad Share", price: "₱3,299/person" }, { label: "Triple Share", price: "₱4,199/person" }, { label: "Twin Share", price: "₱5,299/person" }, { label: "Solo", price: "₱9,899" }, { label: "Sneak-in Child (3–6 yrs)", price: "₱1,897" }] },
      { label: "Standard B", hotels: "Citadines Amigo, Days Hotel by Wyndham Iloilo, Goldberry Lite Hotel", rates: [{ label: "5 Pax", price: "₱3,899/person" }, { label: "Quad Share", price: "₱4,599/person" }, { label: "Triple Share", price: "₱5,199/person" }, { label: "Twin Share", price: "₱6,099/person" }, { label: "Solo", price: "₱11,499" }, { label: "Sneak-in Child (3–6 yrs)", price: "₱1,897" }] },
      { label: "4-Star", hotels: "Park Inn, Seda Atria", rates: [{ label: "Triple Share", price: "₱6,999/person" }, { label: "Twin Share", price: "₱8,499/person" }, { label: "Solo", price: "₱15,199" }, { label: "Sneak-in Child (3–6 yrs)", price: "₱1,897" }] },
    ],
    inclusions: ["3D2N Hotel Accommodation", "Daily Hotel Breakfast", "Round Trip Airport Transfers"],
    exclusions: ["Round-trip Airfare", "Other Meals and Personal Expenses", "Hotel Security Deposit"],
    itinerary: [
      { day: "Day 1", title: "Arrival", details: "Arrival at Iloilo Airport. Transfer to hotel. Free time. Overnight." },
      { day: "Day 2", title: "Free Time / Optional Tours", details: "Breakfast. Free time or optional tours." },
      { day: "Day 3", title: "Departure", details: "Breakfast. Free time or optional tours. Check-out. Transfer to airport." },
    ],
    optionalTours: [
      { name: "Gigantes Island Tour", price: "₱2,249/person | Pick up: 4:00–5:00 AM from Iloilo City", details: "Antonia Beach, Bantigue Sand Bar, Tangke Lagoon, Lantangan Beach, Tinagong Baybay, Cabugao Gamay Island, Palupandan Island. Includes: Lunch (5 menus), All Environmental & Entrance Fees, Kayak & Paddle Board (subject to avail.), Drone Shots, Roundtrip Hotel–Bancal Port–Hotel" },
    ],
    notes: ["Hotel check-in: 2:00–3:00 PM | Check-out: 12:00 PM", "Rates subject to change without prior notice"],
  },
  {
    name: "Balabac", slug: "balabac", tagline: "Palawan's last frontier",
    image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=600&q=80&fit=crop",
    hero: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=1400&q=90&fit=crop",
    package: "4D3N Balabac Land Arrangement",
    hotelCategories: [
      { label: "Budget (PPS Night)", hotels: "Las Residencias B&B, Royale Parc Hotel, Casa Belina, Casañas Suites w/ Pool", rates: [{ label: "5 Pax", price: "₱13,899/person" }, { label: "Quad Share", price: "₱14,799/person" }, { label: "Triple Share", price: "₱14,899/person" }, { label: "Twin Share", price: "₱15,099/person" }, { label: "Solo", price: "₱16,799" }, { label: "Sneak-in Child (5–7 yrs)", price: "₱9,100" }] },
      { label: "Standard A (PPS Night)", hotels: "Blue Lagoon Inn & Suites, Marianne Hotel, Rema Tourist Inn, Ala Amid B&B, Balay Tuko Garden Inn, Sheridan Boutique", rates: [{ label: "5 Pax", price: "₱14,899/person" }, { label: "Quad Share", price: "₱14,999/person" }, { label: "Triple Share", price: "₱15,299/person" }, { label: "Twin Share", price: "₱15,299/person" }, { label: "Solo", price: "₱17,199" }] },
      { label: "Standard B (PPS Night)", hotels: "Sunlight Hotels & Resorts, Acacia Tree Garden Hotel, Panja Resort, Palawan Uno, Holiday Suites, White Breeze Palawan Hotel, Microtel by Wyndham PPS", rates: [{ label: "5 Pax", price: "₱15,399/person" }, { label: "Quad Share", price: "₱15,499/person" }, { label: "Triple Share", price: "₱15,799/person" }, { label: "Twin Share", price: "₱16,199/person" }, { label: "Solo", price: "₱18,899" }] },
      { label: "4-Star (PPS Night)", hotels: "Aziza Paradise Hotel, Astoria Palawan, Costa Palawan Resort, HUE Hotels, The Ivywall Hotel", rates: [{ label: "5 Pax", price: "₱15,799/person" }, { label: "Quad Share", price: "₱16,499/person" }, { label: "Triple Share", price: "₱16,999/person" }, { label: "Twin Share", price: "₱17,299/person" }, { label: "Solo", price: "₱21,199" }] },
      { label: "5-Star (PPS Night)", hotels: "Princesa Garden Island Resort and Spa", rates: [{ label: "Quad Share", price: "₱18,399/person" }, { label: "Triple Share", price: "₱18,399/person" }, { label: "Twin Share", price: "₱18,799/person" }, { label: "Solo", price: "₱24,099" }] },
    ],
    inclusions: ["1 Night Hotel Accommodation in PPS", "Roundtrip Transfer (Airport–Hotel–Airport)", "Free WiFi and Hotel Facilities", "2 Nights at Candaraman Island", "Breakfast, Lunch, Dinner (Balabac)", "Van Transfers", "Entrance, Cottage, Environmental Fees", "Tour Guide", "Travel Insurance"],
    exclusions: ["Round-trip Airfare", "Hotel Security Deposit", "Onok Overnight Fee: ₱1,000/person"],
    itinerary: [
      { day: "Day 1", title: "Arrival in PPS", details: "Arrival at Puerto Princesa Airport. Transfer to hotel. Check-in." },
      { day: "Day 2", title: "Travel to Balabac", details: "3:00–4:00 AM Pick up, depart to Buliluyan Port (5 hrs land travel)\n9:00–9:30 AM Tourist registration\n9:30–10:00 AM Big Boat to Bancalaan Island\n10:30 AM–4:00 PM Island Hopping (Tangkahan, Patawan, Coral Garden)\n5:00 PM Candaraman Island overnight" },
      { day: "Day 3", title: "Island Hopping", details: "6:00–7:00 AM Breakfast\n8:00 AM–4:00 PM Island Hopping (Candaraman Island, Starfish Island, Nasugbata Reef, Onok Island)\n5:00 PM Overnight at Onok or Candaraman" },
      { day: "Day 4", title: "Departure", details: "5:00–5:30 AM Call time\n6:00 AM Depart Balabac to Buliluyan Port\n9:00 AM Arrival at Buliluyan, van to PPS\n2:00–3:00 PM Arrival in PPS (Drop Off)" },
    ],
    notes: ["Select early arrival flight", "Schedule departure flight 5:00 PM onwards", "Itinerary may vary by weather conditions"],
  },
  {
    name: "Puerto Princesa", slug: "puerto-princesa", tagline: "Home of the Underground River",
    image: "https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?w=600&q=80&fit=crop",
    hero: "https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?w=1400&q=90&fit=crop",
    videoUrl: "https://bit.ly/GDX-PPS-VID",
    package: "3D2N Puerto Princesa Land Arrangement",
    hotelCategories: [
      { label: "Budget", hotels: "Las Residencias B&B, Royale Parc Hotel, Casa Belina, Casañas Suites w/ Pool", rates: [{ label: "Buy 2 Take 2", price: "₱5,699/person" }, { label: "Buy 2 Take 1", price: "₱4,649/person" }, { label: "Sneak-in Child (3–6 yrs)", price: "₱1,599" }, { label: "Airport Transfer", price: "FREE" }] },
      { label: "Standard A", hotels: "Blue Lagoon Inn & Suites, Marianne Hotel, Rema Tourist Inn, Ala Amid B&B, Balay Tuko Garden Inn, Marianne Home Inn, Sheridan Boutique Hotel", rates: [{ label: "Buy 2 Take 2", price: "₱6,899/person" }, { label: "Buy 2 Take 1", price: "₱5,849/person" }, { label: "Sneak-in Child (3–6 yrs)", price: "₱1,599" }, { label: "Free Airport Transfer", price: "8AM–4PM only" }] },
      { label: "Standard B", hotels: "Sunlight Hotels & Resorts, Acacia Tree Garden Hotel, Panja Resort, Palawan Uno, Holiday Suites, White Breeze Palawan Hotel, Microtel by Wyndham PPS", rates: [{ label: "Buy 2 Take 2", price: "₱8,999/person" }, { label: "Buy 2 Take 1", price: "₱7,349/person" }, { label: "Sneak-in Child (3–6 yrs)", price: "₱1,599" }] },
      { label: "4-Star", hotels: "Aziza Paradise Hotel, Astoria Palawan, Costa Palawan Resort, HUE Hotels & Resorts, The Ivywall Hotel", rates: [{ label: "Buy 2 Take 2", price: "₱12,799/person" }, { label: "Buy 2 Take 1", price: "₱11,099/person" }, { label: "Sneak-in Child (3–6 yrs)", price: "₱1,599" }] },
      { label: "5-Star", hotels: "Princesa Garden Island Resort and Spa w/ Pool", rates: [{ label: "Buy 2 Take 2", price: "₱20,599/person" }, { label: "Buy 2 Take 1", price: "₱14,099/person" }, { label: "Sneak-in Child (3–6 yrs)", price: "₱1,599" }] },
    ],
    inclusions: ["3D2N Hotel Accommodation", "Daily Hotel Breakfast", "Round Trip Airport Transfers", "Free WiFi", "Free Hotel Facilities"],
    exclusions: ["Round-trip Airfare", "Other Meals and Personal Expenses", "Hotel Security Deposit", "Optional Tours"],
    itinerary: [
      { day: "Day 1", title: "Arrival", details: "Arrival at Puerto Princesa Airport. Transfer to hotel. Check-in." },
      { day: "Day 2", title: "Free Time / Optional Tours", details: "Breakfast. Free time or optional tours." },
      { day: "Day 3", title: "Departure", details: "Breakfast. Check-out. Transfer to airport." },
    ],
    optionalTours: [
      { name: "Underground River Tour", price: "₱2,000/person | Pick up: 7:00–7:30 AM", details: "Sightseeing/Picture taking. Zipline/Mangrove Paddle/Ugong Rock (additional charge). Includes: Van, Licensed Guide, All Permits, Entrance Fees, Boat Fee, Buffet Lunch, Audio" },
      { name: "Honda Bay Island Tour", price: "₱1,550/person | Pick up: 7:30–8:00 AM", details: "Luli Island, Pambato Reef, Cowrie Island. Includes: Van, Guide, Entrance Fees, Boat Fee, Lunch" },
      { name: "City Tour", price: "₱700/person | Morning 7:00–8:00 AM / Afternoon 1:00–2:00 PM", details: "Includes: Van, Guide, Entrance Fees, Light Snacks" },
      { name: "Firefly Watching", price: "₱1,450/person | Pick up: 5:00–5:30 PM", details: "Includes: Van, Guide, Boat Fees, All Permits, Dinner" },
    ],
    notes: ["Environmental Fee: ₱150/person (valid 7 days, all tours)", "At least 1 tour is mandatory per LGU", "Astoria Palawan: Add ₱3,500/way for airport transfer", "Hotel check-in: 2:00–3:00 PM | Check-out: 12:00 PM"],
  },
  {
    name: "El Nido", slug: "el-nido", tagline: "Limestone cliffs and emerald lagoons",
    image: "https://images.unsplash.com/photo-1559128010-7c1ad6e1b6a5?w=600&q=80&fit=crop",
    hero: "https://images.unsplash.com/photo-1559128010-7c1ad6e1b6a5?w=1400&q=90&fit=crop",
    videoUrl: "https://bit.ly/GDX-ELNIDO-VID",
    package: "3D2N El Nido Land Arrangement",
    hotelCategories: [
      { label: "Budget", hotels: "Ricgem Place, La Soledad Guest House, Mananquil Travel Lodge, Nay Aster Pension, Silverise Pension El Nido", rates: [{ label: "Buy 2 Take 2", price: "₱6,799/person (2 paying pax)" }, { label: "Sneak-in Child (3–5 yrs)", price: "₱2,399" }] },
      { label: "Standard A", hotels: "Rovic's Tourist Hotel, Amakan El Nido (no breakfast), Stunning Republic Beach Resort", rates: [{ label: "Buy 2 Take 2", price: "₱9,699/person (2 paying pax)" }, { label: "Sneak-in Child (3–5 yrs)", price: "₱2,399" }] },
      { label: "Standard B", hotels: "Sea Cocoon Hotel, El Nido Garden Resort, Cuna Hotel, Weekends El Nido Beach Resort, El Nido Beach Hotel, Bill Tourist Inn", rates: [{ label: "Buy 2 Take 2", price: "₱13,399/person (2 paying pax)" }, { label: "Sneak-in Child (3–5 yrs)", price: "₱2,399" }] },
      { label: "High-End", hotels: "Ora Beach Resort (Corong Corong), Lio Villas Resort, Suites by Eco Hotels, Charlies El Nido (Lio)", rates: [{ label: "Buy 2 Take 2", price: "₱16,899/person (2 paying pax)" }, { label: "Sneak-in Child (3–5 yrs)", price: "₱2,399" }] },
    ],
    inclusions: ["3D2N Hotel Accommodation", "Daily Breakfast (except Amakan El Nido)", "Round Trip Airport Transfers", "Hotel Taxes and Surcharges"],
    exclusions: ["Round-trip Airfare", "Other Meals and Personal Expenses", "Hotel Security Deposit"],
    itinerary: [
      { day: "Day 1", title: "Arrival", details: "Arrival at Puerto Princesa Airport. Van transfer to El Nido (5 hrs). Check-in. Free time or join optional Nacpan Tour." },
      { day: "Day 2", title: "Free Time / Optional Tours", details: "Breakfast. Free time or optional tours." },
      { day: "Day 3", title: "Departure", details: "Breakfast. Check-out. Transfer back to Puerto Princesa Airport." },
    ],
    optionalTours: [
      { name: "Tour A", price: "₱1,349/person | 8:30 AM", details: "Big Lagoon, Shimizu Island, Secret Lagoon, 7 Commando, Payong Payong Beach" },
      { name: "Tour B", price: "₱1,449/person | 8:30 AM", details: "Snake Island, Cudognon Cave, Pinagbuyutan Island, Cathedral Cave, Pupolkan Snorkeling" },
      { name: "Tour C", price: "₱1,549/person | 8:30 AM", details: "Hidden Beach, Secret Beach, Matinloc Island, Talisay Beach, Helicopter Island" },
      { name: "Tour D", price: "₱1,349/person | 8:30 AM", details: "Small Lagoon, Cadlao Lagoon, Nat-nat Beach, Pasandigan Beach, Paradise Beach" },
      { name: "El Nido Cruise (VIP)", price: "₱2,399/person | 10:00 AM", details: "VIP Island Hopping with Lagoon. Includes: Festive lunch, snacks, lagoon fee, licensed guide, party speaker" },
      { name: "San Vicente Land Tour", price: "₱3,299/person | Pick up: 9:00 AM – Tour ends 4:00 PM", details: "Bigaho Falls, San Vicente Surf" },
    ],
    notes: ["Environmental Fee: ₱400/person (valid 10 days, all tours)", "Lagoon Fee: ₱200/person/lagoon", "Hotel check-in: 2:00–3:00 PM | Check-out: 12:00 PM", "Transfer PPS to El Nido: 7–8AM / 8–9AM / 9–10AM / 1–2PM / 4–5PM / 6–7PM", "El Nido to PPS: 5AM / 6–7AM / 8–9AM / 10–11AM / 12–1PM / 5–6PM"],
  },
  {
    name: "Biliran", slug: "biliran", tagline: "Waterfalls and volcanic hot springs",
    image: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?w=600&q=80&fit=crop",
    hero: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?w=1400&q=90&fit=crop",
    package: "3D2N Biliran — Tres Marias Peak with Ulan-Ulan Falls",
    hotelCategories: [
      { label: "Rates by Group Size", hotels: "", rates: [{ label: "10 Pax", price: "₱3,999/person" }, { label: "9 Pax", price: "₱4,099/person" }, { label: "8 Pax", price: "₱4,299/person" }, { label: "7 Pax", price: "₱4,399/person" }, { label: "6 Pax", price: "₱4,699/person" }, { label: "5 Pax", price: "₱4,699/person" }, { label: "4 Pax", price: "₱4,699/person" }, { label: "3 Pax", price: "₱5,199/person" }, { label: "2 Pax", price: "₱6,299/person" }, { label: "Solo", price: "₱11,199" }] },
    ],
    inclusions: ["DOT Guide", "Entrance Fee", "Environmental Fee", "Certificate", "Guide Tipping", "6 Hosted Meals"],
    exclusions: ["Round-trip Airfare", "Airport Pick-up and Drop-off (rates vary by number of passengers)", "Camping Tent: ₱400 (good for 2 persons)"],
    itinerary: [
      { day: "Day 1", title: "Trek Highlights", details: "Active Volcano • Enchanted Mountain • Mossy Forest • Active Wildlife • Giant Trees • Ulan-ulan Falls (Side Trip)" },
    ],
    notes: ["MAJOR CLIMB — NOT FOR BEGINNERS", "Meet-up in Biliran: 8:00–9:00 AM", "Bringing own tent is allowed | Tent rental: ₱400 (good for 2)", "Final itinerary provided upon confirmation"],
  },
  {
    name: "Mt. Apo", slug: "mt-apo", tagline: "The roof of the Philippines",
    image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=600&q=80&fit=crop",
    hero: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1400&q=90&fit=crop",
    package: "2D1N Mt. Apo via Kapatagan Trail",
    hotelCategories: [
      { label: "Rates by Group Size", hotels: "", rates: [{ label: "10 Pax", price: "₱6,499/person" }, { label: "9 Pax", price: "₱6,699/person" }, { label: "8 Pax", price: "₱6,999/person" }, { label: "7 Pax", price: "₱7,499/person" }, { label: "6 Pax", price: "₱7,999/person" }, { label: "5 Pax", price: "₱8,499/person" }, { label: "4 Pax", price: "₱9,999/person" }, { label: "3 Pax", price: "₱10,499/person" }, { label: "2 Pax", price: "₱12,999/person" }] },
    ],
    inclusions: ["Pick-up and drop-off at Davao City airport or hotel (Poblacion area)", "3 Hosted Meals", "Transportation (Davao–Jump Off return)", "Climb Permit, Certificate, Guide Fee", "Entrance Fee, Exit Fee", "Environmental Fee"],
    exclusions: ["Round-trip Airfare", "Personal Porter", "Camping Gears"],
    itinerary: [
      { day: "Day 1", title: "Ascent", details: "3:00 AM Meet up Chowking Shell Quimpo | 7:00 AM Kapatagan | 8:00 AM Start Trek | 9:00 AM Nong Boy | 10:00 AM Crossing Sabwag | 10:40 AM Baroring Gamay | 12:00 PM Baroring (Lunch) | 2:00 PM Godi-Godi Camp (pitch tent, rest) | 6:00 PM Dinner | 8:00 PM Lights Off" },
      { day: "Day 2", title: "Summit & Descent", details: "12:00 AM Wake up, prepare for ascend | 1:00 AM Start Trek | 6:00 AM White Sand (Breakfast) | 7:30 AM Summit / Sunrise | 8:30 AM Descend to White Sand | 11:00 AM Gudi-Gudi Campsite | 12:00 PM Lunch | 1:00 PM Descend | 4:00 PM Sitio Paradise" },
    ],
    notes: ["Private tours with customized itineraries available upon request"],
  },
  {
    name: "Dumaguete", slug: "dumaguete", tagline: "The city of gentle people",
    image: "https://images.unsplash.com/photo-1516690561799-46d8f74f9abf?w=600&q=80&fit=crop",
    hero: "https://images.unsplash.com/photo-1516690561799-46d8f74f9abf?w=1400&q=90&fit=crop",
    videoUrl: "https://bit.ly/GDX-DUMAGUETE-VID",
    package: "3D2N Dumaguete Land Arrangement",
    hotelCategories: [
      { label: "Budget", hotels: "Blue Horizon Hostel (no breakfast), 2020 Travelers Inn (no breakfast)", rates: [{ label: "Buy 2 Take 2", price: "₱4,299/person" }, { label: "Buy 2 Take 1", price: "₱3,599/person" }, { label: "Sneak-in Child (5–9 yrs)", price: "₱2,099" }] },
      { label: "Standard A", hotels: "Henia Hotel, M.Y. Hotel Dumaguete, Hotel Nicanor (no breakfast)", rates: [{ label: "Buy 2 Take 2", price: "₱6,299/person" }, { label: "Buy 2 Take 1", price: "₱5,099/person" }, { label: "Sneak-in Child (5–9 yrs)", price: "₱2,099" }] },
      { label: "Standard B", hotels: "Sierra Hotel and Resort, Coco Grande Hotel, Hotel Palwa, DCCCO Hotel, The Bricks Hotel, Infinity Diving Resort, Hotel Essencia, Coast Wise Hotel", rates: [{ label: "Buy 2 Take 2", price: "₱7,599/person" }, { label: "Buy 2 Take 1", price: "₱7,349/person" }, { label: "Sneak-in Child (5–9 yrs)", price: "₱2,099" }] },
      { label: "4-Star", hotels: "UNWND Boutique Hotel, Mahi Mahi Dive Resort, Liquid Dive Resort, The Henry Hotel & Resorts", rates: [{ label: "Buy 2 Take 2", price: "₱12,199/person" }, { label: "Buy 2 Take 1", price: "₱10,499/person" }, { label: "Sneak-in Child (5–9 yrs)", price: "₱2,099" }] },
    ],
    inclusions: ["3D2N Hotel Accommodation", "Daily Breakfast (except 2020 Travelers Inn, Blue Horizon, Hotel Nicanor)", "Roundtrip Airport Transfer"],
    exclusions: ["Round-trip Airfare", "Other Meals and Personal Expenses", "Hotel Security Deposit", "Optional Tours"],
    itinerary: [
      { day: "Day 1", title: "Arrival", details: "Arrival at Dumaguete-Sibulan Airport. Transfer to hotel. Free time. Overnight." },
      { day: "Day 2", title: "Free Time / Optional Tours", details: "Breakfast. Free time or optional tours." },
      { day: "Day 3", title: "Departure", details: "Breakfast. Free time. Check-out. Transfer to airport." },
    ],
    notes: ["Infinity Diving Resort: Add ₱1,200/way", "Mahi Mahi: Add ₱1,400/way", "Liquid Dive: Add ₱1,200/way", "Hotel check-in: 2:00–3:00 PM | Check-out: 12:00 PM"],
  },
  {
    name: "Siquijor", slug: "siquijor", tagline: "The mystical island of fire",
    image: "https://images.unsplash.com/photo-1519046904884-53103b34b206?w=600&q=80&fit=crop",
    hero: "https://images.unsplash.com/photo-1519046904884-53103b34b206?w=1400&q=90&fit=crop",
    videoUrl: "https://bit.ly/GDX-SIQUIJOR-VID",
    package: "3D2N Siquijor Land Arrangement",
    hotelCategories: [
      { label: "Budget", hotels: "Islanders Siquijor (no breakfast), Isla Inn, Edmund's Inn & Suites (no breakfast)", rates: [{ label: "Buy 2 Take 2", price: "₱7,899/person" }, { label: "Buy 2 Take 1", price: "₱6,749/person" }, { label: "Sneak-in Child (2–11 yrs)", price: "₱2,799" }] },
      { label: "Standard A", hotels: "Aquamare Beach Camp Resort (no breakfast), Sea View Resort, The Bruce Beach Resort (no breakfast), Tropical Funtasea Rentals (no breakfast)", rates: [{ label: "Buy 2 Take 2", price: "₱10,399/person" }, { label: "Buy 2 Take 1", price: "₱8,699/person" }, { label: "Sneak-in Child (2–11 yrs)", price: "₱2,799" }] },
      { label: "Standard B", hotels: "Nakabalo Guesthouse, Suite Princess Beach", rates: [{ label: "Buy 2 Take 2", price: "₱11,299/person" }, { label: "Buy 2 Take 1", price: "₱9,449/person" }, { label: "Sneak-in Child (2–11 yrs)", price: "₱2,799" }] },
    ],
    inclusions: ["3D2N Hotel Accommodation", "Daily Breakfast (specific hotels)", "Roundtrip Airport Transfer", "Roundtrip Ferry Ticket", "Transfer from Siquijor Port to Hotels"],
    exclusions: ["Round-trip Airfare", "Other Meals and Personal Expenses", "Hotel Security Deposit", "Optional Tours"],
    itinerary: [
      { day: "Day 1", title: "Arrival", details: "Arrival at Dumaguete-Sibulan Airport. Transfer to Siquijor. Check-in. Overnight." },
      { day: "Day 2", title: "Free Time / Optional Tours", details: "Breakfast. Free time or optional tours." },
      { day: "Day 3", title: "Departure", details: "Breakfast. Free time. Check-out. Transfer to Dumaguete airport." },
    ],
    optionalTours: [
      { name: "Coastal Tour", price: "Solo ₱5,599 | 2 pax ₱3,399 | 3 pax ₱2,599 | 4 pax ₱2,199 | 5 pax ₱1,999 | 8+ ₱1,699 | 8:00 AM–5:00 PM", details: "Paliton Beach, Capilay Spring, Pitogo Cliff, Enchanted Balete Tree, St. Isidore Church, Cambugahay Falls, Salagdoong Beach" },
      { name: "Mountain Tour", price: "Solo ₱5,899 | 2 pax ₱3,699 | 3 pax ₱2,899 | 4 pax ₱2,599 | 5 pax ₱2,299 | 8+ ₱1,999 | 8:00 AM–5:00 PM", details: "Sambulawan Underground River, Bolo-Bolo Spring, Lugnason Falls, Kawayan Holiday Resort, Lagaan Falls, Bandilaan" },
      { name: "Siquijor with Snorkeling", price: "Solo ₱6,499 | 2 pax ₱4,199 | 3 pax ₱3,499 | 4 pax ₱3,099 | 5 pax ₱2,899 | 8+ ₱2,599 | 8:00 AM–5:00 PM", details: "Tulapos Marine Sanctuary, Tubod Marine Sanctuary, Caticugan Marine Sanctuary" },
    ],
    notes: ["Aquamare Beach Camp: Add ₱1,700/way from port", "Sea View Resort: Add ₱900/way", "Suite Princess Beach: Add ₱2,000/way"],
  },
  {
    name: "General Santos", slug: "general-santos", tagline: "The tuna capital of the Philippines",
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&q=80&fit=crop",
    hero: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1400&q=90&fit=crop",
    package: "3D2N General Santos Land Arrangement",
    hotelCategories: [
      { label: "Budget", hotels: "RSG Microtel, Hotel Giorgio, Delle Suites", rates: [{ label: "5 Pax", price: "₱2,899/person" }, { label: "Quad Share", price: "₱3,299/person" }, { label: "Triple Share", price: "₱3,999/person" }, { label: "Twin Share", price: "₱4,599/person" }, { label: "Solo", price: "₱7,899" }, { label: "Sneak-in Child (4–9 yrs)", price: "₱2,539" }] },
      { label: "Standard A", hotels: "Anchor Hotel, Dolores Tropicana Resort, Hotel San Marco, Villa Verde Guest House", rates: [{ label: "5 Pax", price: "₱3,899/person" }, { label: "Quad Share", price: "₱4,499/person" }, { label: "Triple Share", price: "₱4,999/person" }, { label: "Twin Share", price: "₱5,699/person" }, { label: "Solo", price: "₱10,699" }, { label: "Sneak-in Child (4–9 yrs)", price: "₱2,539" }] },
      { label: "Standard B", hotels: "Avior Hotel, Greenleaf Hotel", rates: [{ label: "Triple Share", price: "₱5,999/person" }, { label: "Twin Share", price: "₱7,399/person" }, { label: "Solo", price: "₱13,999" }, { label: "Sneak-in Child (4–9 yrs)", price: "₱2,539" }] },
    ],
    inclusions: ["3D2N Hotel Accommodation", "Daily Hotel Breakfast", "Round-trip Transfer (Airport–Hotel–Airport)"],
    exclusions: ["Other Meals and Personal Expenses", "Hotel Security Deposit", "Optional Tours"],
    itinerary: [
      { day: "Day 1", title: "Arrival", details: "Arrival at General Santos International Airport. Transfer to hotel. Free time. Overnight." },
      { day: "Day 2", title: "Free Time / Optional Tours", details: "Breakfast. Free time or optional tours." },
      { day: "Day 3", title: "Departure", details: "Breakfast. Free time. Check-out. Transfer for departure." },
    ],
    notes: ["Dolores Villas: Add ₱500/way for airport transfer and tour", "Hotel check-in: 2:00–3:00 PM | Check-out: 12:00 PM"],
  },
  {
    name: "Malapascua", slug: "malapascua", tagline: "Where thresher sharks meet paradise",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&q=80&fit=crop",
    hero: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1400&q=90&fit=crop",
    package: "3D2N Malapascua Land Arrangement",
    hotelCategories: [
      { label: "Budget", hotels: "Mabuhay Thresher Dive Resort", rates: [{ label: "Quad Share", price: "₱4,999/person" }, { label: "Triple Share", price: "₱5,099/person" }, { label: "Twin Share", price: "₱5,399/person" }, { label: "Solo", price: "₱7,799" }] },
      { label: "Standard A", hotels: "Tepanee Beach Resort, Malapascua Exotic Island, Blanco Beach Resort", rates: [{ label: "Triple Share", price: "₱10,499/person" }, { label: "Twin Share", price: "₱11,299/person" }, { label: "Solo", price: "₱15,199" }] },
    ],
    inclusions: ["3D2N Room Accommodation", "Daily Breakfast (except Budget)", "Round-trip Transfer (Airport–Accommodation–Airport)"],
    exclusions: ["Other Meals and Personal Expenses", "Passenger Boat: ₱200/person/way", "Municipal Ecological Fee: ₱95 (local) / ₱120 (foreign)", "Optional Tours"],
    itinerary: [
      { day: "Day 1", title: "Arrival", details: "Arrival at Mactan International Airport. Transfer to Maya Port. Passenger boat to Malapascua. Transfer to hotel. Free time. Overnight." },
      { day: "Day 2", title: "Free Time / Optional Tours", details: "Breakfast. Free time or optional tours." },
      { day: "Day 3", title: "Departure", details: "Breakfast. Free time. Check-out. Transfer to airport." },
    ],
    notes: ["Passenger boat: First trip 7:00 AM / Last trip 5:00 PM", "Schedule departure flight 5:00 PM onwards", "Hotel check-in: 2:00–3:00 PM | Check-out: 12:00 PM"],
  },
  {
    name: "Zamboanga", slug: "zamboanga", tagline: "Asia's Latin city by the sea",
    image: "https://images.unsplash.com/photo-1521295121783-8a321d551ad2?w=1200&q=90&fit=crop",
    hero: "https://images.unsplash.com/photo-1521295121783-8a321d551ad2?w=1200&q=90&fit=crop",
    package: "3D2N Zamboanga Land Arrangement",
    hotelCategories: [
      { label: "Budget", hotels: "Winzelle Suites, Cityinn Hotel (no breakfast)", rates: [{ label: "Quad Share", price: "₱4,399/person" }, { label: "Triple Share", price: "₱4,899/person" }, { label: "Twin Share", price: "₱4,799/person" }, { label: "Solo", price: "₱6,799" }, { label: "Sneak-in Child (4–9 yrs)", price: "₱3,199" }] },
      { label: "Standard", hotels: "Grand Astoria Hotel, Ever O Business Hotel, Residencia Suites Hotel, Winn Hotel", rates: [{ label: "5 Pax", price: "₱5,699/person" }, { label: "Quad Share", price: "₱5,499/person" }, { label: "Triple Share", price: "₱5,799/person" }, { label: "Twin Share", price: "₱6,199/person" }, { label: "Solo", price: "₱7,699" }, { label: "Sneak-in Child (4–9 yrs)", price: "₱3,199" }] },
      { label: "4-Star", hotels: "L'Meridian Suites, Marcian Garden Hotel, Garden Orchid Hotel", rates: [{ label: "Quad Share", price: "₱6,799/person" }, { label: "Triple Share", price: "₱6,999/person" }, { label: "Twin Share", price: "₱7,499/person" }, { label: "Solo", price: "₱12,199" }, { label: "Sneak-in Child (4–9 yrs)", price: "₱3,199" }] },
    ],
    inclusions: ["3D2N Hotel Accommodation", "Daily Breakfast (except Cityinn Hotel)", "Round-trip Transfer (Airport–Hotel–Airport)"],
    exclusions: ["Other Meals and Personal Expenses", "Hotel Security Deposit", "Optional Tours"],
    itinerary: [
      { day: "Day 1", title: "Arrival", details: "Arrival at Zamboanga International Airport. Transfer to hotel. Free time. Overnight." },
      { day: "Day 2", title: "Free Time / Optional Tours", details: "Breakfast. Free time or optional tours." },
      { day: "Day 3", title: "Departure", details: "Breakfast. Free time. Check-out. Transfer for departure." },
    ],
    notes: ["Hotel check-in: 2:00–3:00 PM | Check-out: 12:00 PM", "Rates subject to change without prior notice"],
  },
  {
    name: "Basilan", slug: "basilan", tagline: "A hidden gem of the Sulu Archipelago",
    image: "https://images.unsplash.com/photo-1505118380757-91f5f5632de0?w=600&q=80&fit=crop",
    hero: "https://images.unsplash.com/photo-1505118380757-91f5f5632de0?w=1400&q=90&fit=crop",
    package: "2D1N Basilan Land Arrangement",
    hotelCategories: [
      { label: "Budget", hotels: "Kasinnahan Hotel", rates: [{ label: "10 Pax", price: "₱8,299/person" }, { label: "9 Pax", price: "₱8,799/person" }, { label: "8 Pax", price: "₱9,099/person" }, { label: "7 Pax", price: "₱9,799/person" }, { label: "6 Pax", price: "₱10,399/person" }, { label: "5 Pax", price: "₱11,699/person" }, { label: "4 Pax", price: "₱13,099/person" }, { label: "3 Pax", price: "₱16,399/person" }, { label: "2 Pax", price: "₱21,499/person" }, { label: "Solo", price: "₱40,499" }, { label: "Child 0–2 yrs", price: "FREE" }, { label: "Child 3–5 yrs", price: "50% less" }, { label: "Child 6 yrs+", price: "Full Payment" }] },
    ],
    inclusions: ["2D1N Hotel Accommodation", "Roundtrip transfers from airport to Zamboanga City sea port", "Roundtrip ferry fare from Zamboanga City", "Roundtrip motorboat from Isabela de Basilan port to Malamawi Island", "Roundtrip land transfers to Pahali Resort", "Entrance and Cottage Fee", "Snacks in Marang-marang floating cottage", "Lunch at Pahali Resort (Day 1)", "AC van transfers for City Tour (Day 2)", "DOT Accredited Tour Guide"],
    exclusions: ["Round-trip Airfare", "Travel Insurance", "Anything not mentioned in inclusions"],
    itinerary: [
      { day: "Day 1", title: "Basilan Island Activities", details: "5:00 AM Pick up at Zamboanga Airport\n6:00 AM Boat departure to Isabela City\n7:30 AM Arrival in Isabela de Basilan\n8:00–10:00 AM Marang-Marang Floating Cottage (kayak, fish feeding, snacks)\n10:00 AM–3:00 PM Pahali Resort (swimming and lunch)\n3:30–4:00 PM Check-in at hotel" },
      { day: "Day 2", title: "Isabela City Tour & Departure", details: "6:30–7:30 AM Breakfast at hotel\n8:30 AM–12:00 PM Isabela City Tour (Geras Mosque, Rubber Plantation, Tagima Marker, Provincial Capitol, HAPI Plaza, Sta. Isabel Cathedral)\n1:30 PM Proceed to sea port\n2:00 PM Depart Isabela City\n3:30–4:00 PM Drop off at Zamboanga Airport" },
    ],
    notes: [],
  },
];