export const DESTINATIONS = [
  { name: "Boracay", slug: "boracay", tagline: "World-famous white beach paradise" },
  { name: "Bantayan", slug: "bantayan", tagline: "Pristine island escape in Cebu" },
  { name: "Batanes", slug: "batanes", tagline: "The rugged beauty of the northernmost isles" },
  { name: "Bacolod", slug: "bacolod", tagline: "The City of Smiles awaits you" },
  { name: "Bohol", slug: "bohol", tagline: "Chocolate Hills and tarsier wonders" },
  { name: "Cebu", slug: "cebu", tagline: "Queen City of the South" },
  { name: "Camiguin", slug: "camiguin", tagline: "Island born of fire, surrounded by sea" },
  { name: "Northern Mindanao", slug: "northern-mindanao", tagline: "Gateway to the heart of Mindanao" },
  { name: "Coron", slug: "coron", tagline: "Crystal lagoons and legendary shipwrecks" },
  { name: "Cagayan de Oro", slug: "cagayan-de-oro", tagline: "The City of Golden Friendship" },
  { name: "Davao", slug: "davao", tagline: "The King City of the South" },
  { name: "Dinagat", slug: "dinagat", tagline: "Untouched island beauty" },
  { name: "Catanduanes", slug: "catanduanes", tagline: "The happy island of the Pacific" },
  { name: "Bukidnon", slug: "bukidnon", tagline: "The highland paradise of Mindanao" },
  { name: "Leyte", slug: "leyte", tagline: "Historic shores and lush landscapes" },
  { name: "Port Barton", slug: "port-barton", tagline: "Palawan's hidden cinematic gem" },
  { name: "Legazpi", slug: "legazpi", tagline: "In the shadow of Mayon Volcano" },
  { name: "Manila", slug: "manila", tagline: "The pearl of the Orient Seas" },
  { name: "Siargao", slug: "siargao", tagline: "The surfing capital of the Philippines" },
  { name: "Samal", slug: "samal", tagline: "Island Garden City of Samal" },
  { name: "Ilo-Ilo", slug: "ilo-ilo", tagline: "Heritage, culture, and breathtaking coastlines" },
  { name: "Balabac", slug: "balabac", tagline: "Palawan's last frontier" },
  { name: "Puerto Princesa", slug: "puerto-princesa", tagline: "Home of the Underground River" },
  { name: "El Nido", slug: "el-nido", tagline: "Limestone cliffs and emerald lagoons" },
  { name: "Biliran", slug: "biliran", tagline: "Waterfalls and volcanic hot springs" },
  { name: "Mt. Apo", slug: "mt-apo", tagline: "The roof of the Philippines" },
  { name: "Dumaguete", slug: "dumaguete", tagline: "The city of gentle people" },
  { name: "Siquijor", slug: "siquijor", tagline: "The mystical island of fire" },
  { name: "General Santos", slug: "general-santos", tagline: "The tuna capital of the Philippines" },
  { name: "Malapascua", slug: "malapascua", tagline: "Where thresher sharks meet paradise" },
  { name: "Zamboanga", slug: "zamboanga", tagline: "Asia's Latin city by the sea" },
  { name: "Basilan", slug: "basilan", tagline: "A hidden gem of the Sulu Archipelago" },
];