-- sync-fusioo is scheduled via cron-job.org (pg_cron not available on this project).
--
-- Cron job config:
--   URL:      https://snploarndnyuxapqpegi.supabase.co/functions/v1/sync-fusioo
--   Schedule: every 30 minutes
--   Headers:
--     Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNucGxvYXJuZG55dXhhcHFwZWdpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODM2NjM2NjYsImV4cCI6MjA5OTIzOTY2Nn0.WwxbaAUXkscntqSQrA4MNNaAhRO5S788ydwfvj0JoPo
--     Content-Type: application/json
